// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_MethodTest_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_MethodTest_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_MethodTest__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_MethodTest__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_MethodTest_void_method__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_MethodTest_set_value__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_MethodTest_get_value__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_MethodTest_add__SWIG_0(jarg1: *const c_void, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_MethodTest_static_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_static_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_MethodTest_const_method__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_MethodTest_with_default__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_MethodTest_with_default__SWIG_1(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_MethodTest__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_free_void__SWIG_0();
    }

    extern "C" {
        pub fn Rust_free_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Rust wrapper for C++ class MethodTest
/// Holds a pointer to the underlying C++ object.
pub struct MethodTest {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class MethodTest
pub trait MethodTestTrait {
    fn void_method(&mut self);
    fn set_value(&mut self, v: i32);
    fn get_value(&mut self) -> i32;
    fn add(&mut self, a: i32, b: i32) -> i32;
    fn static_add(&mut self, a: i32, b: i32) -> i32;
    fn const_method(&mut self) -> i32;
    fn with_default_int_int(&mut self, a: i32, b: i32) -> i32;
    fn with_default_int(&mut self, a: i32) -> i32;
}

impl MethodTest {
    pub fn value_set(&self, value: i32) {
        unsafe { ffi::Rust_MethodTest_value_set__SWIG_0(self.ptr, value) }
    }
}

impl MethodTest {
    pub fn value(&self) -> i32 {
        unsafe { ffi::Rust_MethodTest_value_get__SWIG_0(self.ptr) }
    }
}

impl MethodTest {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_MethodTest__SWIG_0() },
        }
    }
}

impl MethodTest {
    pub fn new_int(v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_MethodTest__SWIG_1(v) },
        }
    }
}

impl MethodTest {
    pub fn MethodTest_static_add_int_int(a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_MethodTest_static_add__SWIG_0(a, b) }
    }
}

impl MethodTest {
    pub fn static_add_int_int(a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_static_add__SWIG_0(a, b) }
    }
}

impl Drop for MethodTest {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_MethodTest__SWIG_0(self.ptr) }
    }
}

impl MethodTest {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl MethodTestTrait for MethodTest {
    fn void_method(&mut self) {
        unsafe { ffi::Rust_MethodTest_void_method__SWIG_0(self.ptr) }
    }
    fn set_value(&mut self, v: i32) {
        unsafe { ffi::Rust_MethodTest_set_value__SWIG_0(self.ptr, v) }
    }
    fn get_value(&mut self) -> i32 {
        unsafe { ffi::Rust_MethodTest_get_value__SWIG_0(self.ptr) }
    }
    fn add(&mut self, a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_MethodTest_add__SWIG_0(self.ptr, a, b) }
    }
    fn static_add(&mut self, a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_static_add__SWIG_0(self.ptr, a, b) }
    }
    fn const_method(&mut self) -> i32 {
        unsafe { ffi::Rust_MethodTest_const_method__SWIG_0(self.ptr) }
    }
    fn with_default_int_int(&mut self, a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_MethodTest_with_default__SWIG_0(self.ptr, a, b) }
    }
    fn with_default_int(&mut self, a: i32) -> i32 {
        unsafe { ffi::Rust_MethodTest_with_default__SWIG_1(self.ptr, a) }
    }
}

pub fn free_void() {
    unsafe { ffi::Rust_free_void__SWIG_0() }
}

pub fn free_add_int_int(a: i32, b: i32) -> i32 {
    unsafe { ffi::Rust_free_add__SWIG_0(a, b) }
}

