// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_INT_CONST__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_DOUBLE_CONST__SWIG_0() -> c_double;
    }

    extern "C" {
        pub fn Rust_STR_CONST__SWIG_0() -> *const c_char;
    }

    extern "C" {
        pub fn Rust_global_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_global_double__SWIG_0() -> c_double;
    }

    extern "C" {
        pub fn Rust_CLASS_CONST__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_static_var__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_instance_var__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_ConstClass__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_ConstClass_get_value__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_ConstClass_set_value__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_delete_ConstClass__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

pub fn INT_CONST() -> i32 {
    unsafe { ffi::Rust_INT_CONST__SWIG_0() }
}

pub fn DOUBLE_CONST() -> f64 {
    unsafe { ffi::Rust_DOUBLE_CONST__SWIG_0() }
}

pub fn STR_CONST() -> &str {
    unsafe { ffi::Rust_STR_CONST__SWIG_0() }
}

pub fn global_int() -> i32 {
    unsafe { ffi::Rust_global_int__SWIG_0() }
}

pub fn global_double() -> f64 {
    unsafe { ffi::Rust_global_double__SWIG_0() }
}

/// Rust wrapper for C++ class ConstClass
/// Holds a pointer to the underlying C++ object.
pub struct ConstClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class ConstClass
pub trait ConstClassTrait {
    fn get_value(&self) -> i32;
    fn set_value(&mut self, v: i32);
}

impl ConstClass {
    pub fn new_int() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_ConstClass__SWIG_0() },
        }
    }
}

impl Drop for ConstClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_ConstClass__SWIG_0(self.ptr) }
    }
}

impl ConstClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl ConstClassTrait for ConstClass {
    fn get_value(&mut self) -> i32 {
        unsafe { ffi::Rust_ConstClass_get_value__SWIG_0(self.ptr) }
    }
    fn set_value(&mut self, v: i32) {
        unsafe { ffi::Rust_ConstClass_set_value__SWIG_0(self.ptr, v) }
    }
}

