// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_new_StructWithEnums__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_some_enum__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test1__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: *mut c_void, jarg4: *mut c_void);
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test2__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: *mut c_void, jarg4: *mut c_void);
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test3__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test4__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test5__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test6__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test7__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_StructWithEnums_enum_test8__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_StructWithEnums__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_hola__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_hi__SWIG_0() -> c_int;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class StructWithEnums
/// Holds a pointer to the underlying C++ object.
pub struct StructWithEnums {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StructWithEnums
pub trait StructWithEnumsTrait {
    fn enum_test1(&mut self, param1: i32, param2: *mut c_void, param3: *mut c_void);
    fn enum_test2(&mut self, param1: i32, param2: *mut c_void, param3: *mut c_void);
    fn enum_test3(&mut self) -> SWIGENUM;
    fn enum_test4(&mut self) -> SWIGENUM;
    fn enum_test5(&mut self) -> SWIGENUM;
    fn enum_test6(&mut self) -> SWIGENUM;
    fn enum_test7(&mut self) -> SWIGENUM;
    fn enum_test8(&mut self) -> SWIGENUM;
}

impl StructWithEnums {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StructWithEnums__SWIG_0() },
        }
    }
}

impl Drop for StructWithEnums {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StructWithEnums__SWIG_0(self.ptr) }
    }
}

impl StructWithEnums {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StructWithEnumsTrait for StructWithEnums {
    fn enum_test1(&mut self, param1: i32, param2: *mut c_void, param3: *mut c_void) {
        unsafe { ffi::Rust_StructWithEnums_enum_test1__SWIG_0(self.ptr, param1, param2, param3) }
    }
    fn enum_test2(&mut self, param1: i32, param2: *mut c_void, param3: *mut c_void) {
        unsafe { ffi::Rust_StructWithEnums_enum_test2__SWIG_0(self.ptr, param1, param2, param3) }
    }
    fn enum_test3(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test3__SWIG_0(self.ptr) }
    }
    fn enum_test4(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test4__SWIG_0(self.ptr) }
    }
    fn enum_test5(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test5__SWIG_0(self.ptr) }
    }
    fn enum_test6(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test6__SWIG_0(self.ptr) }
    }
    fn enum_test7(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test7__SWIG_0(self.ptr) }
    }
    fn enum_test8(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_StructWithEnums_enum_test8__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
}

pub fn hi() -> i32 {
    unsafe { ffi::Rust_hi__SWIG_0() }
}

