// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_static_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticMemberTest_grab_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_grab_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_StaticMemberTest__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_StaticMemberTest__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_StaticFunctionTest_static_func__SWIG_0();
    }

    extern "C" {
        pub fn Rust_static_func__SWIG_0();
    }

    extern "C" {
        pub fn Rust_StaticFunctionTest_static_func_2__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_static_func_2__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_StaticFunctionTest_static_func_3__SWIG_0(jarg1: c_int, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_static_func_3__SWIG_0(jarg1: c_int, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_new_StaticFunctionTest__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_StaticFunctionTest__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_statty__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticBase_grab_statty_base__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_grab_statty_base__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_StaticBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_StaticBase__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_statty__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticDerived_grab_statty_derived__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_grab_statty_derived__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_StaticDerived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_StaticDerived__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_is_python_builtin__SWIG_0() -> c_uchar;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class StaticMemberTest
/// Holds a pointer to the underlying C++ object.
pub struct StaticMemberTest {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StaticMemberTest
pub trait StaticMemberTestTrait {
    fn grab_int(&mut self) -> i32;
}

impl StaticMemberTest {
    pub fn StaticMemberTest_grab_int() -> i32 {
        unsafe { ffi::Rust_StaticMemberTest_grab_int__SWIG_0() }
    }
}

impl StaticMemberTest {
    pub fn grab_int() -> i32 {
        unsafe { ffi::Rust_grab_int__SWIG_0() }
    }
}

impl StaticMemberTest {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticMemberTest__SWIG_0() },
        }
    }
}

impl Drop for StaticMemberTest {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StaticMemberTest__SWIG_0(self.ptr) }
    }
}

impl StaticMemberTest {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StaticMemberTestTrait for StaticMemberTest {
    fn grab_int(&mut self) -> i32 {
        unsafe { ffi::Rust_grab_int__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class StaticFunctionTest
/// Holds a pointer to the underlying C++ object.
pub struct StaticFunctionTest {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StaticFunctionTest
pub trait StaticFunctionTestTrait {
    fn static_func(&mut self);
    fn static_func_2(&mut self, param_1: i32);
    fn static_func_3(&mut self, param_1: i32, param_2: i32);
}

impl StaticFunctionTest {
    pub fn StaticFunctionTest_static_func() {
        unsafe { ffi::Rust_StaticFunctionTest_static_func__SWIG_0() }
    }
}

impl StaticFunctionTest {
    pub fn static_func() {
        unsafe { ffi::Rust_static_func__SWIG_0() }
    }
}

impl StaticFunctionTest {
    pub fn StaticFunctionTest_static_func_2_int(param_1: i32) {
        unsafe { ffi::Rust_StaticFunctionTest_static_func_2__SWIG_0(param_1) }
    }
}

impl StaticFunctionTest {
    pub fn static_func_2_int(param_1: i32) {
        unsafe { ffi::Rust_static_func_2__SWIG_0(param_1) }
    }
}

impl StaticFunctionTest {
    pub fn StaticFunctionTest_static_func_3_int_int(param_1: i32, param_2: i32) {
        unsafe { ffi::Rust_StaticFunctionTest_static_func_3__SWIG_0(param_1, param_2) }
    }
}

impl StaticFunctionTest {
    pub fn static_func_3_int_int(param_1: i32, param_2: i32) {
        unsafe { ffi::Rust_static_func_3__SWIG_0(param_1, param_2) }
    }
}

impl StaticFunctionTest {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticFunctionTest__SWIG_0() },
        }
    }
}

impl Drop for StaticFunctionTest {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StaticFunctionTest__SWIG_0(self.ptr) }
    }
}

impl StaticFunctionTest {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StaticFunctionTestTrait for StaticFunctionTest {
    fn static_func(&mut self) {
        unsafe { ffi::Rust_static_func__SWIG_0(self.ptr) }
    }
    fn static_func_2(&mut self, param_1: i32) {
        unsafe { ffi::Rust_static_func_2__SWIG_0(self.ptr, param_1) }
    }
    fn static_func_3(&mut self, param_1: i32, param_2: i32) {
        unsafe { ffi::Rust_static_func_3__SWIG_0(self.ptr, param_1, param_2) }
    }
}

/// Rust wrapper for C++ class StaticBase
/// Holds a pointer to the underlying C++ object.
pub struct StaticBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StaticBase
pub trait StaticBaseTrait {
    fn grab_statty_base(&mut self) -> i32;
}

impl StaticBase {
    pub fn StaticBase_grab_statty_base() -> i32 {
        unsafe { ffi::Rust_StaticBase_grab_statty_base__SWIG_0() }
    }
}

impl StaticBase {
    pub fn grab_statty_base() -> i32 {
        unsafe { ffi::Rust_grab_statty_base__SWIG_0() }
    }
}

impl Drop for StaticBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StaticBase__SWIG_0(self.ptr) }
    }
}

impl StaticBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticBase__SWIG_0() },
        }
    }
}

impl StaticBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StaticBaseTrait for StaticBase {
    fn grab_statty_base(&mut self) -> i32 {
        unsafe { ffi::Rust_grab_statty_base__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class StaticDerived
/// Holds a pointer to the underlying C++ object.
pub struct StaticDerived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StaticDerived
pub trait StaticDerivedTrait: StaticBaseTrait {
    fn grab_statty_derived(&mut self) -> i32;
}

impl StaticDerived {
    pub fn StaticDerived_grab_statty_derived() -> i32 {
        unsafe { ffi::Rust_StaticDerived_grab_statty_derived__SWIG_0() }
    }
}

impl StaticDerived {
    pub fn grab_statty_derived() -> i32 {
        unsafe { ffi::Rust_grab_statty_derived__SWIG_0() }
    }
}

impl StaticDerived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticDerived__SWIG_0() },
        }
    }
}

impl Drop for StaticDerived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StaticDerived__SWIG_0(self.ptr) }
    }
}

impl StaticDerived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class StaticBase
    pub fn as_StaticBase(&self) -> &StaticBase {
        // SAFETY: The pointer is valid and points to a StaticBase
        unsafe { &*(self.ptr as *const StaticBase) }
    }

    /// Upcast to base class StaticBase (mutable)
    pub fn as_StaticBase_mut(&mut self) -> &mut StaticBase {
        // SAFETY: The pointer is valid and points to a StaticBase
        unsafe { &mut *(self.ptr as *mut StaticBase) }
    }
}

impl StaticDerivedTrait for StaticDerived {
    fn grab_statty_derived(&mut self) -> i32 {
        unsafe { ffi::Rust_grab_statty_derived__SWIG_0(self.ptr) }
    }
}

pub fn is_python_builtin() -> bool {
    unsafe { ffi::Rust_is_python_builtin__SWIG_0() }
}

