// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_Foo_bar__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Foo_sbar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_sbar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_something__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_UnnamedStruct__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_UnnamedStruct__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_something__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_TypedefNamedStruct_m__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_TypedefNamedStruct__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_TypedefNamedStruct__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Test_test1__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Test_test2__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Test_test3__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Test_test4__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Test__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
    fn bar(&mut self) -> Foo::SomeOtherBar *;
    fn sbar(&mut self) -> Foo::SomeOtherBar *;
}

impl Foo {
    pub fn Foo_sbar() -> Foo::SomeOtherBar * {
        unsafe { ffi::Rust_Foo_sbar__SWIG_0() }
    }
}

impl Foo {
    pub fn sbar() -> Foo::SomeOtherBar * {
        unsafe { ffi::Rust_sbar__SWIG_0() }
    }
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
    fn bar(&mut self) -> Foo::SomeOtherBar * {
        unsafe { ffi::Rust_Foo_bar__SWIG_0(self.ptr) }
    }
    fn sbar(&mut self) -> Foo::SomeOtherBar * {
        unsafe { ffi::Rust_sbar__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class UnnamedStruct
/// Holds a pointer to the underlying C++ object.
pub struct UnnamedStruct {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class UnnamedStruct
pub trait UnnamedStructTrait {
}

impl UnnamedStruct {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_UnnamedStruct__SWIG_0() },
        }
    }
}

impl Drop for UnnamedStruct {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_UnnamedStruct__SWIG_0(self.ptr) }
    }
}

impl UnnamedStruct {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl UnnamedStructTrait for UnnamedStruct {
}

/// Rust wrapper for C++ class TypedefNamedStruct
/// Holds a pointer to the underlying C++ object.
pub struct TypedefNamedStruct {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class TypedefNamedStruct
pub trait TypedefNamedStructTrait {
    fn m(&mut self);
}

impl TypedefNamedStruct {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_TypedefNamedStruct__SWIG_0() },
        }
    }
}

impl Drop for TypedefNamedStruct {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_TypedefNamedStruct__SWIG_0(self.ptr) }
    }
}

impl TypedefNamedStruct {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl TypedefNamedStructTrait for TypedefNamedStruct {
    fn m(&mut self) {
        unsafe { ffi::Rust_TypedefNamedStruct_m__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Test
/// Holds a pointer to the underlying C++ object.
pub struct Test {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test
pub trait TestTrait {
    fn test1(&mut self, a: *mut c_void) -> UnnamedStruct *;
    fn test2(&mut self, a: *mut c_void) -> NamedStruct *;
    fn test3(&mut self, a: *mut c_void) -> TypedefNamedStruct *;
    fn test4(&mut self, a: *mut c_void) -> DoubleTypedef *;
}

impl Test {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test__SWIG_0() },
        }
    }
}

impl Drop for Test {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test__SWIG_0(self.ptr) }
    }
}

impl Test {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl TestTrait for Test {
    fn test1(&mut self, a: *mut c_void) -> UnnamedStruct * {
        unsafe { ffi::Rust_Test_test1__SWIG_0(self.ptr, a) }
    }
    fn test2(&mut self, a: *mut c_void) -> NamedStruct * {
        unsafe { ffi::Rust_Test_test2__SWIG_0(self.ptr, a) }
    }
    fn test3(&mut self, a: *mut c_void) -> TypedefNamedStruct * {
        unsafe { ffi::Rust_Test_test3__SWIG_0(self.ptr, a) }
    }
    fn test4(&mut self, a: *mut c_void) -> DoubleTypedef * {
        unsafe { ffi::Rust_Test_test4__SWIG_0(self.ptr, a) }
    }
}

