// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_fact__SWIG_0(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_Foo__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Test__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Test_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_weird__SWIG_0(jarg1: *mut c_char, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_do_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_do_method2__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_delete_Test2__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Test2_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Test2__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Test3_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Test3__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test3__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Test4_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Test4__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test4__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_foo3__SWIG_0(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_Test5_method__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Test5__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test5__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_do_method3__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> *mut c_char;
    }

}

// Safe wrapper functions

pub fn fact_int(n: i32) -> i32 {
    unsafe { ffi::Rust_fact__SWIG_0(n) }
}

pub fn Foo() -> i32 {
    unsafe { ffi::Rust_Foo__SWIG_0() }
}

/// Rust wrapper for C++ class Test
/// Holds a pointer to the underlying C++ object.
pub struct Test {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test
pub trait TestTrait {
    fn method(&mut self) -> c_char;
}

impl Test {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test__SWIG_0() },
        }
    }
}

impl Drop for Test {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test__SWIG_0(self.ptr) }
    }
}

impl Test {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl TestTrait for Test {
    fn method(&mut self) -> c_char {
        unsafe { ffi::Rust_Test_method__SWIG_0(self.ptr) }
    }
}

pub fn weird_example::Bad_::Bad(x: String, y: i32) {
    unsafe { ffi::Rust_weird__SWIG_0(x, y) }
}

pub fn do_method_example::TestPtr(t: *mut c_void) -> String {
    unsafe { ffi::Rust_do_method__SWIG_0(t) }
}

pub fn do_method2_example::TestPtr(t: *mut c_void) -> String {
    unsafe { ffi::Rust_do_method2__SWIG_0(t) }
}

/// Rust wrapper for C++ class Test2
/// Holds a pointer to the underlying C++ object.
pub struct Test2 {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test2
pub trait Test2Trait {
    fn method(&mut self) -> c_char;
}

impl Drop for Test2 {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test2__SWIG_0(self.ptr) }
    }
}

impl Test2 {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test2__SWIG_0() },
        }
    }
}

impl Test2 {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl Test2Trait for Test2 {
    fn method(&mut self) -> c_char {
        unsafe { ffi::Rust_Test2_method__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Test3
/// Holds a pointer to the underlying C++ object.
pub struct Test3 {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test3
pub trait Test3Trait: Test2Trait {
    fn method(&mut self) -> c_char;
}

impl Test3 {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test3__SWIG_0() },
        }
    }
}

impl Drop for Test3 {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test3__SWIG_0(self.ptr) }
    }
}

impl Test3 {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Test2
    pub fn as_Test2(&self) -> &Test2 {
        // SAFETY: The pointer is valid and points to a Test2
        unsafe { &*(self.ptr as *const Test2) }
    }

    /// Upcast to base class Test2 (mutable)
    pub fn as_Test2_mut(&mut self) -> &mut Test2 {
        // SAFETY: The pointer is valid and points to a Test2
        unsafe { &mut *(self.ptr as *mut Test2) }
    }
}

impl Test3Trait for Test3 {
    fn method(&mut self) -> c_char {
        unsafe { ffi::Rust_Test3_method__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Test4
/// Holds a pointer to the underlying C++ object.
pub struct Test4 {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test4
pub trait Test4Trait: Test3Trait {
    fn method(&mut self) -> c_char;
}

impl Test4 {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test4__SWIG_0() },
        }
    }
}

impl Drop for Test4 {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test4__SWIG_0(self.ptr) }
    }
}

impl Test4 {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Test3
    pub fn as_Test3(&self) -> &Test3 {
        // SAFETY: The pointer is valid and points to a Test3
        unsafe { &*(self.ptr as *const Test3) }
    }

    /// Upcast to base class Test3 (mutable)
    pub fn as_Test3_mut(&mut self) -> &mut Test3 {
        // SAFETY: The pointer is valid and points to a Test3
        unsafe { &mut *(self.ptr as *mut Test3) }
    }
}

impl Test4Trait for Test4 {
    fn method(&mut self) -> c_char {
        unsafe { ffi::Rust_Test4_method__SWIG_0(self.ptr) }
    }
}

pub fn foo3_Foo2::Integer(x: i32) -> i32 {
    unsafe { ffi::Rust_foo3__SWIG_0(x) }
}

/// Rust wrapper for C++ class Test5
/// Holds a pointer to the underlying C++ object.
pub struct Test5 {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test5
pub trait Test5Trait: Test3Trait {
    fn method(&mut self) -> c_char;
}

impl Test5 {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test5__SWIG_0() },
        }
    }
}

impl Drop for Test5 {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test5__SWIG_0(self.ptr) }
    }
}

impl Test5 {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Test3
    pub fn as_Test3(&self) -> &Test3 {
        // SAFETY: The pointer is valid and points to a Test3
        unsafe { &*(self.ptr as *const Test3) }
    }

    /// Upcast to base class Test3 (mutable)
    pub fn as_Test3_mut(&mut self) -> &mut Test3 {
        // SAFETY: The pointer is valid and points to a Test3
        unsafe { &mut *(self.ptr as *mut Test3) }
    }
}

impl Test5Trait for Test5 {
    fn method(&mut self) -> c_char {
        unsafe { ffi::Rust_Test5_method__SWIG_0(self.ptr) }
    }
}

