// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn SwigDirector_CallbackBase_new_director(rust_director: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_CallbackBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackBase_on_event__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackBase_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_CallbackBase_trigger_event__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackBase_call_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_CallbackBase__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_disown_CallbackBase(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_callback__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_CallbackUser__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_CallbackUser__SWIG_1(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_CallbackUser_set_callback__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackUser_get_callback__SWIG_0(jarg1: *const c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_CallbackUser_notify__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackUser_process_value__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_CallbackUser__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

/// Trait for Rust implementations of CallbackBase that can be used as Director callbacks
/// 
/// # Safety
/// 
/// This trait is used for C++ callbacks (Director pattern).
/// C++ may call back into Rust during method execution.
/// Methods use `&self` by default to allow safe re-entrancy.
/// - Use `Cell<T>` for simple mutable state (Copy types)
/// - Use `RefCell<T>` for complex state (panics on re-entrancy)
pub trait CallbackBaseDirector {
    fn on_event(&self, event_id: i32);
    fn process(&self, value: i32) -> Option<i32>;
}

impl CallbackBase {
    /// Create a new CallbackBase with a Rust Director implementation
    /// 
    /// # Arguments
    /// * `director` - A Rust implementation of CallbackBaseDirector
    /// 
    /// # Safety
    /// The returned CallbackBase holds a C++ object that calls back into Rust.
    /// The director must remain valid for the lifetime of the CallbackBase.
    pub fn new_with_trait<D: CallbackBaseDirector + 'static>(director: D) -> Self {
        let director_box = Box::new(director);
        let director_ptr = Box::into_raw(director_box) as *mut c_void;
        Self {
            ptr: unsafe { ffi::SwigDirector_CallbackBase_new_director(director_ptr) },
        }
    }
}

/// Rust wrapper for C++ class CallbackBase
/// Holds a pointer to the underlying C++ object.
pub struct CallbackBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CallbackBase
pub trait CallbackBaseTrait {
    fn on_event(&mut self, event_id: i32);
    fn process(&mut self, value: i32) -> i32;
    fn trigger_event(&mut self, id: i32);
    fn call_process(&mut self, v: i32) -> i32;
}

impl Drop for CallbackBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CallbackBase__SWIG_0(self.ptr) }
    }
}

impl CallbackBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackBase__SWIG_0() },
        }
    }
}

impl CallbackBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl CallbackBaseTrait for CallbackBase {
    fn on_event(&mut self, event_id: i32) {
        unsafe { ffi::Rust_CallbackBase_on_event__SWIG_0(self.ptr, event_id) }
    }
    fn process(&mut self, value: i32) -> i32 {
        unsafe { ffi::Rust_CallbackBase_process__SWIG_0(self.ptr, value) }
    }
    fn trigger_event(&mut self, id: i32) {
        unsafe { ffi::Rust_CallbackBase_trigger_event__SWIG_0(self.ptr, id) }
    }
    fn call_process(&mut self, v: i32) -> i32 {
        unsafe { ffi::Rust_CallbackBase_call_process__SWIG_0(self.ptr, v) }
    }
}

/// Rust wrapper for C++ class CallbackUser
/// Holds a pointer to the underlying C++ object.
pub struct CallbackUser {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CallbackUser
pub trait CallbackUserTrait {
    fn set_callback(&mut self);
    fn get_callback(&self) -> CallbackBase *;
    fn notify(&mut self, event_id: i32);
    fn process_value(&mut self, v: i32) -> i32;
}

impl CallbackUser {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackUser__SWIG_0() },
        }
    }
}

impl CallbackUser {
    pub fn new_CallbackBase() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackUser__SWIG_1() },
        }
    }
}

impl Drop for CallbackUser {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CallbackUser__SWIG_0(self.ptr) }
    }
}

impl CallbackUser {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl CallbackUserTrait for CallbackUser {
    fn set_callback(&mut self, cb: *mut c_void) {
        unsafe { ffi::Rust_CallbackUser_set_callback__SWIG_0(self.ptr, cb) }
    }
    fn get_callback(&mut self) -> CallbackBase * {
        unsafe { ffi::Rust_CallbackUser_get_callback__SWIG_0(self.ptr) }
    }
    fn notify(&mut self, event_id: i32) {
        unsafe { ffi::Rust_CallbackUser_notify__SWIG_0(self.ptr, event_id) }
    }
    fn process_value(&mut self, v: i32) -> i32 {
        unsafe { ffi::Rust_CallbackUser_process_value__SWIG_0(self.ptr, v) }
    }
}

