// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn SwigDirector_CallbackBase_new_director_vtable(vtable: *mut c_void, rust_director: *mut c_void) -> *mut c_void;
        pub fn SwigDirector_CallbackBase_drop_director(rust_director: *mut c_void);
    }

    extern "C" {
        pub fn Rust_delete_CallbackBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackBase_on_event__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackBase_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_CallbackBase_trigger_event__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackBase_call_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_CallbackBase__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_disown_CallbackBase(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackUser_callback_set__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackUser_callback_get__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_CallbackUser__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_CallbackUser__SWIG_1(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_CallbackUser_set_callback__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_CallbackUser_get_callback__SWIG_0(jarg1: *const c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_CallbackUser_notify__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_CallbackUser_process_value__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_CallbackUser__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Trait for Rust implementations of CallbackBase that can be used as Director callbacks
/// 
/// # Safety
/// 
/// This trait is used for C++ callbacks (Director pattern).
/// C++ may call back into Rust during method execution.
/// Methods use `&self` by default to allow safe re-entrancy.
/// - Use `Cell<T>` for simple mutable state (Copy types)
/// - Use `RefCell<T>` for complex state (panics on re-entrancy)
pub trait CallbackBaseDirector {
    fn on_event_int(&self, event_id: i32);
    fn process_int(&self, value: i32) -> Option<i32>;
}

/// VTable for CallbackBase director callbacks
/// Each field is a function pointer that calls the corresponding trait method
#[repr(C)]
pub struct CallbackBaseVTable {
    pub on_event_int: unsafe extern "C" fn(*const c_void, i32) -> bool,
    pub process_int: unsafe extern "C" fn(*const c_void, *mut i32, i32) -> bool,
}

/// Thunk function for CallbackBase::on_event_int (VTable entry)
/// Casts the data pointer to type D and calls the trait method
pub unsafe extern "C" fn CallbackBase_thunk_on_event_int<D: CallbackBaseDirector>(data: *const c_void, event_id: i32) -> bool {
    let obj = &*(data as *const D);
    obj.on_event_int(event_id);
    true
}

/// Thunk function for CallbackBase::process_int (VTable entry)
/// Casts the data pointer to type D and calls the trait method
pub unsafe extern "C" fn CallbackBase_thunk_process_int<D: CallbackBaseDirector>(data: *const c_void, result: *mut i32, value: i32) -> bool {
    let obj = &*(data as *const D);
    match obj.process_int(value) {
        Some(v) => { *result = v; true }
        None => false,
    }
}

/// Trait that provides a static VTable for CallbackBaseDirector implementations
/// Each implementing type automatically gets a VTable through blanket impl
pub trait CallbackBaseVTableProvider: CallbackBaseDirector + Sized {
    const VTABLE: CallbackBaseVTable = CallbackBaseVTable {
        on_event_int: CallbackBase_thunk_on_event_int::<Self>,
        process_int: CallbackBase_thunk_process_int::<Self>,
    };
}

/// Blanket implementation: all Sized types implementing CallbackBaseDirector get VTableProvider
impl<T: CallbackBaseDirector + Sized> CallbackBaseVTableProvider for T {}

impl CallbackBase {
    /// Create a new CallbackBase with a Rust Director implementation using VTable
    /// 
    /// This uses associated constants for zero-overhead virtual dispatch.
    /// Requires Rust 1.20+
    pub fn new_with_vtable<D: CallbackBaseDirector + Sized + 'static>(director: D) -> Self {
        // Get the VTable through the VTableProvider trait
        let vtable: &'static CallbackBaseVTable = &<D as CallbackBaseVTableProvider>::VTABLE;
        // Box the director object
        let director_ptr = Box::into_raw(Box::new(director)) as *mut c_void;
        // Pass both vtable and director pointer to C++
        Self {
            ptr: unsafe { ffi::SwigDirector_CallbackBase_new_director_vtable(vtable as *const CallbackBaseVTable as *mut c_void, director_ptr) },
        }
    }
}

// Drop function for CallbackBase director (called from C++ destructor)
#[no_mangle]
pub unsafe extern "C" fn SwigDirector_CallbackBase_drop_director(director: *mut c_void) {
    // Reconstruct the Box<D> and let it drop
    // Note: We don't know the concrete type D here, but we only need to free the memory
    // The actual Drop impl will be called when the Box is dropped
    // We use a helper to drop as Box<dyn Director> to invoke proper cleanup
    let _ = Box::from_raw(director as *mut ());
}

/// Rust wrapper for C++ class CallbackBase
/// Holds a pointer to the underlying C++ object.
pub struct CallbackBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CallbackBase
pub trait CallbackBaseTrait {
    fn on_event(&mut self, event_id: i32);
    fn process(&mut self, value: i32) -> i32;
    fn trigger_event(&mut self, id: i32);
    fn call_process(&mut self, v: i32) -> i32;
}

impl Drop for CallbackBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CallbackBase__SWIG_0(self.ptr) }
    }
}

impl CallbackBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackBase__SWIG_0() },
        }
    }
}

impl CallbackBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl CallbackBaseTrait for CallbackBase {
    fn on_event(&mut self, event_id: i32) {
        unsafe { ffi::Rust_CallbackBase_on_event__SWIG_0(self.ptr, event_id) }
    }
    fn process(&mut self, value: i32) -> i32 {
        unsafe { ffi::Rust_CallbackBase_process__SWIG_0(self.ptr, value) }
    }
    fn trigger_event(&mut self, id: i32) {
        unsafe { ffi::Rust_CallbackBase_trigger_event__SWIG_0(self.ptr, id) }
    }
    fn call_process(&mut self, v: i32) -> i32 {
        unsafe { ffi::Rust_CallbackBase_call_process__SWIG_0(self.ptr, v) }
    }
}

/// Rust wrapper for C++ class CallbackUser
/// Holds a pointer to the underlying C++ object.
pub struct CallbackUser {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CallbackUser
pub trait CallbackUserTrait {
    fn set_callback(&mut self, cb: *mut c_void);
    fn get_callback(&mut self) -> CallbackBase;
    fn notify(&mut self, event_id: i32);
    fn process_value(&mut self, v: i32) -> i32;
}

impl CallbackUser {
    pub fn callback_set(&self, callback: *mut c_void) {
        unsafe { ffi::Rust_CallbackUser_callback_set__SWIG_0(self.ptr, callback) }
    }
}

impl CallbackUser {
    pub fn callback(&self) -> *mut c_void {
        unsafe { ffi::Rust_CallbackUser_callback_get__SWIG_0(self.ptr) }
    }
}

impl CallbackUser {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackUser__SWIG_0() },
        }
    }
}

impl CallbackUser {
    pub fn new_CallbackBase(cb: *mut c_void) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CallbackUser__SWIG_1(cb) },
        }
    }
}

impl Drop for CallbackUser {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CallbackUser__SWIG_0(self.ptr) }
    }
}

impl CallbackUser {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl CallbackUserTrait for CallbackUser {
    fn set_callback(&mut self, cb: *mut c_void) {
        unsafe { ffi::Rust_CallbackUser_set_callback__SWIG_0(self.ptr, cb) }
    }
    fn get_callback(&mut self) -> CallbackBase {
        CallbackBase { ptr: unsafe { ffi::Rust_CallbackUser_get_callback__SWIG_0(self.ptr) } }
    }
    fn notify(&mut self, event_id: i32) {
        unsafe { ffi::Rust_CallbackUser_notify__SWIG_0(self.ptr, event_id) }
    }
    fn process_value(&mut self, v: i32) -> i32 {
        unsafe { ffi::Rust_CallbackUser_process_value__SWIG_0(self.ptr, v) }
    }
}

