// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn SwigDirector_IntBase_new_director(rust_director: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_IntBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_IntBase__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_IntBase__SWIG_1() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_IntBase_apply__SWIG_0(jarg1: *const c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_disown_IntBase(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_IntDerived_apply__SWIG_0(jarg1: *const c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_IntDerived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_IntDerived__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_apply__SWIG_0(jarg1: *const c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn SwigDirector_BoolBase_new_director(rust_director: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BoolBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BoolBase__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_BoolBase_apply__SWIG_0(jarg1: *const c_void, jarg2: c_uchar, jarg3: c_uchar) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_disown_BoolBase(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_BoolDerived_apply__SWIG_0(jarg1: *const c_void, jarg2: c_uchar, jarg3: c_uchar) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_new_BoolDerived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BoolDerived__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_apply__SWIG_1(jarg1: *const c_void, jarg2: c_uchar, jarg3: c_uchar) -> c_uchar;
    }

}

// Safe wrapper functions

/// Trait for Rust implementations of IntBase that can be used as Director callbacks
/// 
/// # Safety
/// 
/// This trait is used for C++ callbacks (Director pattern).
/// C++ may call back into Rust during method execution.
/// Methods use `&self` by default to allow safe re-entrancy.
/// - Use `Cell<T>` for simple mutable state (Copy types)
/// - Use `RefCell<T>` for complex state (panics on re-entrancy)
pub trait IntBaseDirector {
    fn apply(&self, x: i32) -> Option<i32>;
}

impl IntBase {
    /// Create a new IntBase with a Rust Director implementation
    /// 
    /// # Arguments
    /// * `director` - A Rust implementation of IntBaseDirector
    /// 
    /// # Safety
    /// The returned IntBase holds a C++ object that calls back into Rust.
    /// The director must remain valid for the lifetime of the IntBase.
    pub fn new_with_trait<D: IntBaseDirector + 'static>(director: D) -> Self {
        let director_box = Box::new(director);
        let director_ptr = Box::into_raw(director_box) as *mut c_void;
        Self {
            ptr: unsafe { ffi::SwigDirector_IntBase_new_director(director_ptr) },
        }
    }
}

/// Rust wrapper for C++ class IntBase
/// Holds a pointer to the underlying C++ object.
pub struct IntBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class IntBase
pub trait IntBaseTrait {
    fn apply(&self, x: i32) -> i32;
}

impl Drop for IntBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_IntBase__SWIG_0(self.ptr) }
    }
}

impl IntBase {
    pub fn new_int() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_IntBase__SWIG_0() },
        }
    }
}

impl IntBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_IntBase__SWIG_1() },
        }
    }
}

impl IntBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl IntBaseTrait for IntBase {
    fn apply(&mut self, x: i32) -> i32 {
        unsafe { ffi::Rust_IntBase_apply__SWIG_0(self.ptr, x) }
    }
}

/// Rust wrapper for C++ class IntDerived
/// Holds a pointer to the underlying C++ object.
pub struct IntDerived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class IntDerived
pub trait IntDerivedTrait: IntBaseTrait {
    fn apply(&self, x: i32) -> i32;
}

impl IntDerived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_IntDerived__SWIG_0() },
        }
    }
}

impl Drop for IntDerived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_IntDerived__SWIG_0(self.ptr) }
    }
}

impl IntDerived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class IntBase
    pub fn as_IntBase(&self) -> &IntBase {
        // SAFETY: The pointer is valid and points to a IntBase
        unsafe { &*(self.ptr as *const IntBase) }
    }

    /// Upcast to base class IntBase (mutable)
    pub fn as_IntBase_mut(&mut self) -> &mut IntBase {
        // SAFETY: The pointer is valid and points to a IntBase
        unsafe { &mut *(self.ptr as *mut IntBase) }
    }
}

impl IntDerivedTrait for IntDerived {
    fn apply(&mut self, x: i32) -> i32 {
        unsafe { ffi::Rust_IntDerived_apply__SWIG_0(self.ptr, x) }
    }
}

/// Trait for Rust implementations of BoolBase that can be used as Director callbacks
/// 
/// # Safety
/// 
/// This trait is used for C++ callbacks (Director pattern).
/// C++ may call back into Rust during method execution.
/// Methods use `&self` by default to allow safe re-entrancy.
/// - Use `Cell<T>` for simple mutable state (Copy types)
/// - Use `RefCell<T>` for complex state (panics on re-entrancy)
pub trait BoolBaseDirector {
    fn apply(&self, a: bool, b: bool) -> Option<bool>;
}

impl BoolBase {
    /// Create a new BoolBase with a Rust Director implementation
    /// 
    /// # Arguments
    /// * `director` - A Rust implementation of BoolBaseDirector
    /// 
    /// # Safety
    /// The returned BoolBase holds a C++ object that calls back into Rust.
    /// The director must remain valid for the lifetime of the BoolBase.
    pub fn new_with_trait<D: BoolBaseDirector + 'static>(director: D) -> Self {
        let director_box = Box::new(director);
        let director_ptr = Box::into_raw(director_box) as *mut c_void;
        Self {
            ptr: unsafe { ffi::SwigDirector_BoolBase_new_director(director_ptr) },
        }
    }
}

/// Rust wrapper for C++ class BoolBase
/// Holds a pointer to the underlying C++ object.
pub struct BoolBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BoolBase
pub trait BoolBaseTrait {
    fn apply(&self, a: bool, b: bool) -> bool;
}

impl Drop for BoolBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BoolBase__SWIG_0(self.ptr) }
    }
}

impl BoolBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BoolBase__SWIG_0() },
        }
    }
}

impl BoolBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BoolBaseTrait for BoolBase {
    fn apply(&mut self, a: bool, b: bool) -> bool {
        unsafe { ffi::Rust_BoolBase_apply__SWIG_0(self.ptr, a, b) }
    }
}

/// Rust wrapper for C++ class BoolDerived
/// Holds a pointer to the underlying C++ object.
pub struct BoolDerived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BoolDerived
pub trait BoolDerivedTrait: BoolBaseTrait {
    fn apply(&self, a: bool, b: bool) -> bool;
}

impl BoolDerived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BoolDerived__SWIG_0() },
        }
    }
}

impl Drop for BoolDerived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BoolDerived__SWIG_0(self.ptr) }
    }
}

impl BoolDerived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class BoolBase
    pub fn as_BoolBase(&self) -> &BoolBase {
        // SAFETY: The pointer is valid and points to a BoolBase
        unsafe { &*(self.ptr as *const BoolBase) }
    }

    /// Upcast to base class BoolBase (mutable)
    pub fn as_BoolBase_mut(&mut self) -> &mut BoolBase {
        // SAFETY: The pointer is valid and points to a BoolBase
        unsafe { &mut *(self.ptr as *mut BoolBase) }
    }
}

impl BoolDerivedTrait for BoolDerived {
    fn apply(&mut self, a: bool, b: bool) -> bool {
        unsafe { ffi::Rust_BoolDerived_apply__SWIG_0(self.ptr, a, b) }
    }
}

