// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_bar1__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_bar2__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_bar3__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_GlobalInstance_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_GlobalInstance_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Foo_e_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_Foo_e_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_iFoo_e_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_iFoo_e_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_iFoo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_iFoo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_enumInstance_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_enumInstance_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Slap_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_Slap_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Mine_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_Mine_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Thigh_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_Thigh_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_pThigh_set__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_pThigh_get__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_arrayContainYourself_set__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_arrayContainYourself_get__SWIG_0() -> *mut c_void;
    }

}

use std::os::raw::*;

// Safe wrapper functions

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum foo1 {
    CSP_ITERATION_FWD,
    CSP_ITERATION_BWD = 11,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum foo3 {
    ABCDE = 0,
    FGHJI = 1,
}

pub fn bar1_foo1(x: foo1) {
    unsafe { ffi::Rust_bar1__SWIG_0(x) }
}

pub fn bar2_foo2(x: foo2) {
    unsafe { ffi::Rust_bar2__SWIG_0(x) }
}

pub fn bar3_foo3(x: foo3) {
    unsafe { ffi::Rust_bar3__SWIG_0(x) }
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum sad {
    boo,
    hoo = 5,
}

pub const globalinstance1: i32 = 0;
pub const globalinstance2: i32 = 1;
pub const globalinstance3: i32 = 30;
pub fn GlobalInstance_set_int(GlobalInstance: i32) {
    unsafe { ffi::Rust_GlobalInstance_set__SWIG_0(GlobalInstance) }
}

pub fn GlobalInstance_get() -> i32 {
    unsafe { ffi::Rust_GlobalInstance_get__SWIG_0() }
}

pub const AnonEnum1: i32 = 0;
pub const AnonEnum2: i32 = 100;
/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
}

pub const BAR1: i32 = 0;
pub const BAR2: i32 = 1;
impl Foo {
    pub fn set_e(&self, e: i32) {
        unsafe { ffi::Rust_Foo_e_set__SWIG_0(self.ptr, e) }
    }
}

impl Foo {
    pub fn e(&self) -> i32 {
        unsafe { ffi::Rust_Foo_e_get__SWIG_0(self.ptr) }
    }
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
}

/// Rust wrapper for C++ class iFoo
/// Holds a pointer to the underlying C++ object.
pub struct iFoo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class iFoo
pub trait iFooTrait {
}

pub const Phoo: i32 = +50;
pub const Char: i32 = 'a';
impl iFoo {
    pub fn set_e(&self, e: i32) {
        unsafe { ffi::Rust_iFoo_e_set__SWIG_0(self.ptr, e) }
    }
}

impl iFoo {
    pub fn e(&self) -> i32 {
        unsafe { ffi::Rust_iFoo_e_get__SWIG_0(self.ptr) }
    }
}

impl iFoo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_iFoo__SWIG_0() },
        }
    }
}

impl Drop for iFoo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_iFoo__SWIG_0(self.ptr) }
    }
}

impl iFoo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl iFooTrait for iFoo {
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Exclamation {
    goodness,
    gracious,
    me,
}

pub fn enumInstance_set_Exclamation(enumInstance: Exclamation) {
    unsafe { ffi::Rust_enumInstance_set__SWIG_0(enumInstance) }
}

pub fn enumInstance_get() -> enum Exclamation {
    unsafe { ffi::Rust_enumInstance_get__SWIG_0() }
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ContainYourself {
    slap = 10,
    mine,
    thigh,
}

pub fn Slap_set_ContainYourself(Slap: ContainYourself) {
    unsafe { ffi::Rust_Slap_set__SWIG_0(Slap) }
}

pub fn Slap_get() -> enum ContainYourself {
    unsafe { ffi::Rust_Slap_get__SWIG_0() }
}

pub fn Mine_set_ContainYourself(Mine: ContainYourself) {
    unsafe { ffi::Rust_Mine_set__SWIG_0(Mine) }
}

pub fn Mine_get() -> enum ContainYourself {
    unsafe { ffi::Rust_Mine_get__SWIG_0() }
}

pub fn Thigh_set_ContainYourself(Thigh: ContainYourself) {
    unsafe { ffi::Rust_Thigh_set__SWIG_0(Thigh) }
}

pub fn Thigh_get() -> enum ContainYourself {
    unsafe { ffi::Rust_Thigh_get__SWIG_0() }
}

pub fn pThigh_get() -> *mut c_void {
    unsafe { ffi::Rust_pThigh_get__SWIG_0() }
}

pub fn arrayContainYourself_set_enum ContainYourself(arrayContainYourself: &[enum ContainYourself [3]; 3]) {
    unsafe { ffi::Rust_arrayContainYourself_set__SWIG_0(arrayContainYourself) }
}

pub fn arrayContainYourself_get() -> &[enum ContainYourself [3]; 3] {
    unsafe { ffi::Rust_arrayContainYourself_get__SWIG_0() }
}

