// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_bar1__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_bar2__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_bar3__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_GlobalInstance__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_e__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_e__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_iFoo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_iFoo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_enumInstance__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Slap__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Mine__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Thigh__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_pThigh__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_arrayContainYourself__SWIG_0() -> *mut c_void;
    }

}

// Safe wrapper functions

pub fn bar1_foo1(x: foo1) {
    unsafe { ffi::Rust_bar1__SWIG_0(x) }
}

pub fn bar2_foo2(x: foo2) {
    unsafe { ffi::Rust_bar2__SWIG_0(x) }
}

pub fn bar3_foo3(x: foo3) {
    unsafe { ffi::Rust_bar3__SWIG_0(x) }
}

pub fn GlobalInstance() -> i32 {
    unsafe { ffi::Rust_GlobalInstance__SWIG_0() }
}

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
}

/// Rust wrapper for C++ class iFoo
/// Holds a pointer to the underlying C++ object.
pub struct iFoo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class iFoo
pub trait iFooTrait {
}

impl iFoo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_iFoo__SWIG_0() },
        }
    }
}

impl Drop for iFoo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_iFoo__SWIG_0(self.ptr) }
    }
}

impl iFoo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl iFooTrait for iFoo {
}

pub fn enumInstance() -> enum Exclamation {
    unsafe { ffi::Rust_enumInstance__SWIG_0() }
}

pub fn Slap() -> enum ContainYourself {
    unsafe { ffi::Rust_Slap__SWIG_0() }
}

pub fn Mine() -> enum ContainYourself {
    unsafe { ffi::Rust_Mine__SWIG_0() }
}

pub fn Thigh() -> enum ContainYourself {
    unsafe { ffi::Rust_Thigh__SWIG_0() }
}

pub fn pThigh() -> *mut c_void {
    unsafe { ffi::Rust_pThigh__SWIG_0() }
}

pub fn arrayContainYourself() -> &[enum ContainYourself [3]; 3] {
    unsafe { ffi::Rust_arrayContainYourself__SWIG_0() }
}

