// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_new_EnumClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_EnumClass_get_status__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_EnumClass_set_status__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_delete_EnumClass__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_get_favorite_color__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_get_default_size__SWIG_0() -> c_int;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class EnumClass
/// Holds a pointer to the underlying C++ object.
pub struct EnumClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class EnumClass
pub trait EnumClassTrait {
    fn get_status(&self) -> SWIGENUM;
    fn set_status(&mut self, s: i32);
}

impl EnumClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_EnumClass__SWIG_0() },
        }
    }
}

impl Drop for EnumClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_EnumClass__SWIG_0(self.ptr) }
    }
}

impl EnumClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl EnumClassTrait for EnumClass {
    fn get_status(&mut self) -> SWIGENUM {
        unsafe { ffi::Rust_EnumClass_get_status__SWIG_0(self.ptr) }
    }
    fn set_status(&mut self, s: i32) {
        unsafe { ffi::Rust_EnumClass_set_status__SWIG_0(self.ptr, s) }
    }
}

pub fn get_favorite_color() -> Color {
    unsafe { ffi::Rust_get_favorite_color__SWIG_0() }
}

pub fn get_default_size() -> Size {
    unsafe { ffi::Rust_get_default_size__SWIG_0() }
}

