// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_Foo__SWIG_0() -> *const c_char;
    }

    extern "C" {
        pub fn Rust_CBase_Foo__SWIG_0(jarg1: *mut c_void) -> *const c_char;
    }

    extern "C" {
        pub fn Rust_new_CBase__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_CBase__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_CDerived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_CDerived__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn Foo() -> &str {
    unsafe { ffi::Rust_Foo__SWIG_0() }
}

/// Rust wrapper for C++ class CBase
/// Holds a pointer to the underlying C++ object.
pub struct CBase {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CBase
pub trait CBaseTrait {
    fn Foo(&self) -> c_char;
}

impl CBase {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CBase__SWIG_0() },
        }
    }
}

impl Drop for CBase {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CBase__SWIG_0(self.ptr) }
    }
}

impl CBase {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl CBaseTrait for CBase {
    fn Foo(&self) -> c_char {
        unsafe { ffi::Rust_CBase_Foo__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class CDerived
/// Holds a pointer to the underlying C++ object.
pub struct CDerived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class CDerived
pub trait CDerivedTrait: CBaseTrait {
}

impl CDerived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_CDerived__SWIG_0() },
        }
    }
}

impl Drop for CDerived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_CDerived__SWIG_0(self.ptr) }
    }
}

impl CDerived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class CBase
    pub fn as_CBase(&self) -> &CBase {
        // SAFETY: The pointer is valid and points to a CBase
        unsafe { &*(self.ptr as *const CBase) }
    }

    /// Upcast to base class CBase (mutable)
    pub fn as_CBase_mut(&mut self) -> &mut CBase {
        // SAFETY: The pointer is valid and points to a CBase
        unsafe { &mut *(self.ptr as *mut CBase) }
    }
}

impl CDerivedTrait for CDerived {
}

