// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_outer_var_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_outer_var_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_outer_func__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_OuterClass_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_OuterClass_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_OuterClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_OuterClass_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_OuterClass__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_inner_var_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_inner_var_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_inner_func__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_InnerClass_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_InnerClass_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_InnerClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_InnerClass_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_InnerClass__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn outer_var_set_int(Outer::outer_var: i32) {
    unsafe { ffi::Rust_outer_var_set__SWIG_0(Outer::outer_var) }
}

pub fn outer_var_get() -> i32 {
    unsafe { ffi::Rust_outer_var_get__SWIG_0() }
}

pub fn outer_func() -> i32 {
    unsafe { ffi::Rust_outer_func__SWIG_0() }
}

/// Rust wrapper for C++ class OuterClass
/// Holds a pointer to the underlying C++ object.
pub struct OuterClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class OuterClass
pub trait OuterClassTrait {
    fn method(&mut self) -> i32;
}

impl OuterClass {
    pub fn set_value(&self, value: i32) {
        unsafe { ffi::Rust_OuterClass_value_set__SWIG_0(self.ptr, value) }
    }
}

impl OuterClass {
    pub fn value(&self) -> i32 {
        unsafe { ffi::Rust_OuterClass_value_get__SWIG_0(self.ptr) }
    }
}

impl OuterClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OuterClass__SWIG_0() },
        }
    }
}

impl Drop for OuterClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_OuterClass__SWIG_0(self.ptr) }
    }
}

impl OuterClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl OuterClassTrait for OuterClass {
    fn method(&mut self) -> i32 {
        unsafe { ffi::Rust_OuterClass_method__SWIG_0(self.ptr) }
    }
}

pub fn inner_var_set_int(Outer::Inner::inner_var: i32) {
    unsafe { ffi::Rust_inner_var_set__SWIG_0(Outer::Inner::inner_var) }
}

pub fn inner_var_get() -> i32 {
    unsafe { ffi::Rust_inner_var_get__SWIG_0() }
}

pub fn inner_func() -> i32 {
    unsafe { ffi::Rust_inner_func__SWIG_0() }
}

/// Rust wrapper for C++ class InnerClass
/// Holds a pointer to the underlying C++ object.
pub struct InnerClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class InnerClass
pub trait InnerClassTrait {
    fn method(&mut self) -> i32;
}

impl InnerClass {
    pub fn set_value(&self, value: i32) {
        unsafe { ffi::Rust_InnerClass_value_set__SWIG_0(self.ptr, value) }
    }
}

impl InnerClass {
    pub fn value(&self) -> i32 {
        unsafe { ffi::Rust_InnerClass_value_get__SWIG_0(self.ptr) }
    }
}

impl InnerClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_InnerClass__SWIG_0() },
        }
    }
}

impl Drop for InnerClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_InnerClass__SWIG_0(self.ptr) }
    }
}

impl InnerClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl InnerClassTrait for InnerClass {
    fn method(&mut self) -> i32 {
        unsafe { ffi::Rust_InnerClass_method__SWIG_0(self.ptr) }
    }
}

