// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_FooBarInt__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_BarFooInt__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_Bar_foo__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Bar__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_a__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Foo_bar__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Test_foo__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Test__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Test__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Bor_foo__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Bor__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Bor__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Foobar_bar__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foobar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foobar__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_FooT_i_quack__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_FooT_i__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FooT_i__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_FooT_H_foo__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_FooT_H_bar__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_FooT_H__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FooT_H__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_FooT_d_moo__SWIG_0(jarg1: *mut c_void, jarg2: c_double) -> c_double;
    }

    extern "C" {
        pub fn Rust_new_FooT_d__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FooT_d__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BarT_H__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BarT_H__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_Poo_i__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Poo_i__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BooT_H__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BooT_H__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BooT_i__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BooT_i__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_EulerT3D_hello__SWIG_0();
    }

    extern "C" {
        pub fn Rust_hello__SWIG_0();
    }

    extern "C" {
        pub fn Rust_EulerT3D_toFrame__SWIG_1(jarg1: c_int, jarg2: c_int, jarg3: c_int);
    }

    extern "C" {
        pub fn Rust_toFrame__SWIG_1(jarg1: c_int, jarg2: c_int, jarg3: c_int);
    }

    extern "C" {
        pub fn Rust_EulerT3D_callint__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_EulerT3D_lessint__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_EulerT3D_callfooi__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_EulerT3D_lessfooi__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_EulerT3D__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_EulerT3D__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_Ala__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Ala_hi__SWIG_1();
    }

    extern "C" {
        pub fn Rust_hi__SWIG_1();
    }

    extern "C" {
        pub fn Rust_delete_Ala__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_File__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_File__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_AudioProperties__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_AudioProperties__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_AudioPropertiesFile__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_AudioPropertiesFile__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_Properties__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Properties__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_PropertiesFile__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_PropertiesFile__SWIG_1() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_PropertiesFile__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_PropertiesFree__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_PropertiesFree__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_FooFilePrivate__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FooFilePrivate__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_FooFile__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FooFile__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_FLACFile__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_FLACFile__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

pub fn FooBarInt_int(t: i32) {
    unsafe { ffi::Rust_FooBarInt__SWIG_0(t) }
}

pub fn BarFooInt_int(t: i32) {
    unsafe { ffi::Rust_BarFooInt__SWIG_0(t) }
}

/// Rust wrapper for C++ class Bar
/// Holds a pointer to the underlying C++ object.
pub struct Bar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bar
pub trait BarTrait {
    fn foo(&mut self, h: i32) -> SWIGENUM;
}

impl Bar {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_0() },
        }
    }
}

impl Drop for Bar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bar__SWIG_0(self.ptr) }
    }
}

impl Bar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BarTrait for Bar {
    fn foo(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_Bar_foo__SWIG_0(self.ptr, h) }
    }
}

pub fn a() -> i32 {
    unsafe { ffi::Rust_a__SWIG_0() }
}

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait: BarTrait {
    fn bar(&mut self, h: i32) -> SWIGENUM;
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Bar
    pub fn as_Bar(&self) -> &Bar {
        // SAFETY: The pointer is valid and points to a Bar
        unsafe { &*(self.ptr as *const Bar) }
    }

    /// Upcast to base class Bar (mutable)
    pub fn as_Bar_mut(&mut self) -> &mut Bar {
        // SAFETY: The pointer is valid and points to a Bar
        unsafe { &mut *(self.ptr as *mut Bar) }
    }
}

impl FooTrait for Foo {
    fn bar(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_Foo_bar__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class Test
/// Holds a pointer to the underlying C++ object.
pub struct Test {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Test
pub trait TestTrait {
    fn foo(&mut self, h: i32) -> SWIGENUM;
}

impl Test {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Test__SWIG_0() },
        }
    }
}

impl Drop for Test {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Test__SWIG_0(self.ptr) }
    }
}

impl Test {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl TestTrait for Test {
    fn foo(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_Test_foo__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class Bor
/// Holds a pointer to the underlying C++ object.
pub struct Bor {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bor
pub trait BorTrait {
    fn foo(&mut self, h: i32) -> SWIGENUM;
}

impl Bor {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bor__SWIG_0() },
        }
    }
}

impl Drop for Bor {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bor__SWIG_0(self.ptr) }
    }
}

impl Bor {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BorTrait for Bor {
    fn foo(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_Bor_foo__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class Foobar
/// Holds a pointer to the underlying C++ object.
pub struct Foobar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foobar
pub trait FoobarTrait: BarTrait {
    fn bar(&mut self, h: i32) -> SWIGENUM;
}

impl Foobar {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foobar__SWIG_0() },
        }
    }
}

impl Drop for Foobar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foobar__SWIG_0(self.ptr) }
    }
}

impl Foobar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Bar
    pub fn as_Bar(&self) -> &Bar {
        // SAFETY: The pointer is valid and points to a Bar
        unsafe { &*(self.ptr as *const Bar) }
    }

    /// Upcast to base class Bar (mutable)
    pub fn as_Bar_mut(&mut self) -> &mut Bar {
        // SAFETY: The pointer is valid and points to a Bar
        unsafe { &mut *(self.ptr as *mut Bar) }
    }
}

impl FoobarTrait for Foobar {
    fn bar(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_Foobar_bar__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class FooT_i
/// Holds a pointer to the underlying C++ object.
pub struct FooT_i {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FooT_i
pub trait FooT_iTrait {
    fn quack(&mut self, h: i32) -> i32;
}

impl FooT_i {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FooT_i__SWIG_0() },
        }
    }
}

impl Drop for FooT_i {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FooT_i__SWIG_0(self.ptr) }
    }
}

impl FooT_i {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooT_iTrait for FooT_i {
    fn quack(&mut self, h: i32) -> i32 {
        unsafe { ffi::Rust_FooT_i_quack__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class FooT_H
/// Holds a pointer to the underlying C++ object.
pub struct FooT_H {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FooT_H
pub trait FooT_HTrait {
    fn foo(&mut self, h: i32) -> SWIGENUM;
    fn bar(&mut self, h: i32) -> SWIGENUM;
}

impl FooT_H {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FooT_H__SWIG_0() },
        }
    }
}

impl Drop for FooT_H {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FooT_H__SWIG_0(self.ptr) }
    }
}

impl FooT_H {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooT_HTrait for FooT_H {
    fn foo(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_FooT_H_foo__SWIG_0(self.ptr, h) }
    }
    fn bar(&mut self, h: i32) -> SWIGENUM {
        unsafe { ffi::Rust_FooT_H_bar__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class FooT_d
/// Holds a pointer to the underlying C++ object.
pub struct FooT_d {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FooT_d
pub trait FooT_dTrait {
    fn moo(&mut self, h: f64) -> f64;
}

impl FooT_d {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FooT_d__SWIG_0() },
        }
    }
}

impl Drop for FooT_d {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FooT_d__SWIG_0(self.ptr) }
    }
}

impl FooT_d {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooT_dTrait for FooT_d {
    fn moo(&mut self, h: f64) -> f64 {
        unsafe { ffi::Rust_FooT_d_moo__SWIG_0(self.ptr, h) }
    }
}

/// Rust wrapper for C++ class BarT_H
/// Holds a pointer to the underlying C++ object.
pub struct BarT_H {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BarT_H
pub trait BarT_HTrait {
}

impl BarT_H {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BarT_H__SWIG_0() },
        }
    }
}

impl Drop for BarT_H {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BarT_H__SWIG_0(self.ptr) }
    }
}

impl BarT_H {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BarT_HTrait for BarT_H {
}

/// Rust wrapper for C++ class Poo_i
/// Holds a pointer to the underlying C++ object.
pub struct Poo_i {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Poo_i
pub trait Poo_iTrait {
}

impl Poo_i {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Poo_i__SWIG_0() },
        }
    }
}

impl Drop for Poo_i {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Poo_i__SWIG_0(self.ptr) }
    }
}

impl Poo_i {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl Poo_iTrait for Poo_i {
}

/// Rust wrapper for C++ class BooT_H
/// Holds a pointer to the underlying C++ object.
pub struct BooT_H {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BooT_H
pub trait BooT_HTrait {
}

impl BooT_H {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BooT_H__SWIG_0() },
        }
    }
}

impl Drop for BooT_H {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BooT_H__SWIG_0(self.ptr) }
    }
}

impl BooT_H {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BooT_HTrait for BooT_H {
}

/// Rust wrapper for C++ class BooT_i
/// Holds a pointer to the underlying C++ object.
pub struct BooT_i {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BooT_i
pub trait BooT_iTrait {
}

impl BooT_i {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BooT_i__SWIG_0() },
        }
    }
}

impl Drop for BooT_i {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BooT_i__SWIG_0(self.ptr) }
    }
}

impl BooT_i {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BooT_iTrait for BooT_i {
}

/// Rust wrapper for C++ class EulerT3D
/// Holds a pointer to the underlying C++ object.
pub struct EulerT3D {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class EulerT3D
pub trait EulerT3DTrait {
    fn hello(&mut self);
    fn toFrame(&self, v_: *mut c_void, vRes: *mut c_void);
    fn callint(&mut self);
    fn lessint(&mut self);
    fn callfooi(&mut self);
    fn lessfooi(&mut self);
}

impl EulerT3D {
    pub fn EulerT3D_hello() {
        unsafe { ffi::Rust_EulerT3D_hello__SWIG_0() }
    }
}

impl EulerT3D {
    pub fn hello() {
        unsafe { ffi::Rust_hello__SWIG_0() }
    }
}

impl EulerT3D {
    pub fn EulerT3D_toFrame_int_int_int(frame_: i32, v_: i32, vRes: i32) {
        unsafe { ffi::Rust_EulerT3D_toFrame__SWIG_1(frame_, v_, vRes) }
    }
}

impl EulerT3D {
    pub fn toFrame_int_int_int(frame_: i32, v_: i32, vRes: i32) {
        unsafe { ffi::Rust_toFrame__SWIG_1(frame_, v_, vRes) }
    }
}

impl EulerT3D {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_EulerT3D__SWIG_0() },
        }
    }
}

impl Drop for EulerT3D {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_EulerT3D__SWIG_0(self.ptr) }
    }
}

impl EulerT3D {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl EulerT3DTrait for EulerT3D {
    fn hello(&mut self) {
        unsafe { ffi::Rust_hello__SWIG_0(self.ptr) }
    }
    fn toFrame(&self, frame_: i32, v_: i32, vRes: i32) {
        unsafe { ffi::Rust_toFrame__SWIG_1(self.ptr, frame_, v_, vRes) }
    }
    fn callint(&mut self, x: *mut c_void) {
        unsafe { ffi::Rust_EulerT3D_callint__SWIG_0(self.ptr, x) }
    }
    fn lessint(&mut self, x: *mut c_void) {
        unsafe { ffi::Rust_EulerT3D_lessint__SWIG_0(self.ptr, x) }
    }
    fn callfooi(&mut self, x: *mut c_void) {
        unsafe { ffi::Rust_EulerT3D_callfooi__SWIG_0(self.ptr, x) }
    }
    fn lessfooi(&mut self, x: *mut c_void) {
        unsafe { ffi::Rust_EulerT3D_lessfooi__SWIG_0(self.ptr, x) }
    }
}

/// Rust wrapper for C++ class Ala
/// Holds a pointer to the underlying C++ object.
pub struct Ala {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Ala
pub trait AlaTrait {
    fn hi(&mut self);
}

impl Ala {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Ala__SWIG_0() },
        }
    }
}

impl Ala {
    pub fn Ala_hi() {
        unsafe { ffi::Rust_Ala_hi__SWIG_1() }
    }
}

impl Ala {
    pub fn hi() {
        unsafe { ffi::Rust_hi__SWIG_1() }
    }
}

impl Drop for Ala {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Ala__SWIG_0(self.ptr) }
    }
}

impl Ala {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl AlaTrait for Ala {
    fn hi(&mut self) {
        unsafe { ffi::Rust_hi__SWIG_1(self.ptr) }
    }
}

/// Rust wrapper for C++ class File
/// Holds a pointer to the underlying C++ object.
pub struct File {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class File
pub trait FileTrait {
}

impl File {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_File__SWIG_0() },
        }
    }
}

impl Drop for File {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_File__SWIG_0(self.ptr) }
    }
}

impl File {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FileTrait for File {
}

/// Rust wrapper for C++ class AudioProperties
/// Holds a pointer to the underlying C++ object.
pub struct AudioProperties {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class AudioProperties
pub trait AudioPropertiesTrait {
}

impl AudioProperties {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_AudioProperties__SWIG_0() },
        }
    }
}

impl Drop for AudioProperties {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_AudioProperties__SWIG_0(self.ptr) }
    }
}

impl AudioProperties {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl AudioPropertiesTrait for AudioProperties {
}

/// Rust wrapper for C++ class AudioPropertiesFile
/// Holds a pointer to the underlying C++ object.
pub struct AudioPropertiesFile {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class AudioPropertiesFile
pub trait AudioPropertiesFileTrait {
}

impl AudioPropertiesFile {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_AudioPropertiesFile__SWIG_0() },
        }
    }
}

impl Drop for AudioPropertiesFile {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_AudioPropertiesFile__SWIG_0(self.ptr) }
    }
}

impl AudioPropertiesFile {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl AudioPropertiesFileTrait for AudioPropertiesFile {
}

/// Rust wrapper for C++ class Properties
/// Holds a pointer to the underlying C++ object.
pub struct Properties {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Properties
pub trait PropertiesTrait: AudioPropertiesTrait {
}

impl Properties {
    pub fn new_TagLib::FLAC::File() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Properties__SWIG_0() },
        }
    }
}

impl Drop for Properties {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Properties__SWIG_0(self.ptr) }
    }
}

impl Properties {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class AudioProperties
    pub fn as_AudioProperties(&self) -> &AudioProperties {
        // SAFETY: The pointer is valid and points to a AudioProperties
        unsafe { &*(self.ptr as *const AudioProperties) }
    }

    /// Upcast to base class AudioProperties (mutable)
    pub fn as_AudioProperties_mut(&mut self) -> &mut AudioProperties {
        // SAFETY: The pointer is valid and points to a AudioProperties
        unsafe { &mut *(self.ptr as *mut AudioProperties) }
    }
}

impl PropertiesTrait for Properties {
}

/// Rust wrapper for C++ class PropertiesFile
/// Holds a pointer to the underlying C++ object.
pub struct PropertiesFile {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class PropertiesFile
pub trait PropertiesFileTrait: AudioPropertiesFileTrait {
}

impl PropertiesFile {
    pub fn new_TagLib::AudioPropertiesFile::File() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_PropertiesFile__SWIG_0() },
        }
    }
}

impl PropertiesFile {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_PropertiesFile__SWIG_1() },
        }
    }
}

impl Drop for PropertiesFile {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_PropertiesFile__SWIG_0(self.ptr) }
    }
}

impl PropertiesFile {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class AudioPropertiesFile
    pub fn as_AudioPropertiesFile(&self) -> &AudioPropertiesFile {
        // SAFETY: The pointer is valid and points to a AudioPropertiesFile
        unsafe { &*(self.ptr as *const AudioPropertiesFile) }
    }

    /// Upcast to base class AudioPropertiesFile (mutable)
    pub fn as_AudioPropertiesFile_mut(&mut self) -> &mut AudioPropertiesFile {
        // SAFETY: The pointer is valid and points to a AudioPropertiesFile
        unsafe { &mut *(self.ptr as *mut AudioPropertiesFile) }
    }
}

impl PropertiesFileTrait for PropertiesFile {
}

/// Rust wrapper for C++ class PropertiesFree
/// Holds a pointer to the underlying C++ object.
pub struct PropertiesFree {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class PropertiesFree
pub trait PropertiesFreeTrait: AudioPropertiesTrait {
}

impl PropertiesFree {
    pub fn new_TagLib::FLAC::File() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_PropertiesFree__SWIG_0() },
        }
    }
}

impl Drop for PropertiesFree {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_PropertiesFree__SWIG_0(self.ptr) }
    }
}

impl PropertiesFree {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class AudioProperties
    pub fn as_AudioProperties(&self) -> &AudioProperties {
        // SAFETY: The pointer is valid and points to a AudioProperties
        unsafe { &*(self.ptr as *const AudioProperties) }
    }

    /// Upcast to base class AudioProperties (mutable)
    pub fn as_AudioProperties_mut(&mut self) -> &mut AudioProperties {
        // SAFETY: The pointer is valid and points to a AudioProperties
        unsafe { &mut *(self.ptr as *mut AudioProperties) }
    }
}

impl PropertiesFreeTrait for PropertiesFree {
}

/// Rust wrapper for C++ class FooFilePrivate
/// Holds a pointer to the underlying C++ object.
pub struct FooFilePrivate {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FooFilePrivate
pub trait FooFilePrivateTrait {
}

impl FooFilePrivate {
    pub fn new_TagLib::AudioPropertiesFile::File() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FooFilePrivate__SWIG_0() },
        }
    }
}

impl Drop for FooFilePrivate {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FooFilePrivate__SWIG_0(self.ptr) }
    }
}

impl FooFilePrivate {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooFilePrivateTrait for FooFilePrivate {
}

/// Rust wrapper for C++ class FooFile
/// Holds a pointer to the underlying C++ object.
pub struct FooFile {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FooFile
pub trait FooFileTrait: PropertiesFileTrait {
}

impl FooFile {
    pub fn new_TagLib::AudioPropertiesFile::File() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FooFile__SWIG_0() },
        }
    }
}

impl Drop for FooFile {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FooFile__SWIG_0(self.ptr) }
    }
}

impl FooFile {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class PropertiesFile
    pub fn as_PropertiesFile(&self) -> &PropertiesFile {
        // SAFETY: The pointer is valid and points to a PropertiesFile
        unsafe { &*(self.ptr as *const PropertiesFile) }
    }

    /// Upcast to base class PropertiesFile (mutable)
    pub fn as_PropertiesFile_mut(&mut self) -> &mut PropertiesFile {
        // SAFETY: The pointer is valid and points to a PropertiesFile
        unsafe { &mut *(self.ptr as *mut PropertiesFile) }
    }
}

impl FooFileTrait for FooFile {
}

/// Rust wrapper for C++ class FLACFile
/// Holds a pointer to the underlying C++ object.
pub struct FLACFile {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class FLACFile
pub trait FLACFileTrait {
}

impl FLACFile {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_FLACFile__SWIG_0() },
        }
    }
}

impl Drop for FLACFile {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_FLACFile__SWIG_0(self.ptr) }
    }
}

impl FLACFile {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FLACFileTrait for FLACFile {
}

