// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_2(jarg1: c_double) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_1(jarg1: *mut c_void, jarg2: c_double) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_2(jarg1: *mut c_void, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_get__SWIG_1(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_OverloadClass__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_add__SWIG_1(jarg1: c_int, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_add__SWIG_2(jarg1: c_double, jarg2: c_double) -> c_double;
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Rust wrapper for C++ class OverloadClass
/// Holds a pointer to the underlying C++ object.
pub struct OverloadClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class OverloadClass
pub trait OverloadClassTrait {
    fn process_int(&mut self, x: i32) -> i32;
    fn process_f64(&mut self, x: f64) -> i32;
    fn process_int_int(&mut self, x: i32, y: i32) -> i32;
    fn get(&mut self) -> i32;
    fn get(&mut self) -> i32;
}

impl OverloadClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_0() },
        }
    }
}

impl OverloadClass {
    pub fn new_int(v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_1(v) },
        }
    }
}

impl OverloadClass {
    pub fn new_f64(v: f64) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_2(v) },
        }
    }
}

impl Drop for OverloadClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_OverloadClass__SWIG_0(self.ptr) }
    }
}

impl OverloadClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl OverloadClassTrait for OverloadClass {
    fn process_int(&mut self, x: i32) -> i32 {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_0(self.ptr, x) }
    }
    fn process_f64(&mut self, x: f64) -> i32 {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_1(self.ptr, x) }
    }
    fn process_int_int(&mut self, x: i32, y: i32) -> i32 {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_2(self.ptr, x, y) }
    }
    fn get(&mut self) -> i32 {
        unsafe { ffi::Rust_OverloadClass_get__SWIG_0(self.ptr) }
    }
    fn get(&mut self) -> i32 {
        unsafe { ffi::Rust_OverloadClass_get__SWIG_1(self.ptr) }
    }
}

pub fn add_int_int(a: i32, b: i32) -> i32 {
    unsafe { ffi::Rust_add__SWIG_0(a, b) }
}

pub fn add_int_int_int(a: i32, b: i32, c: i32) -> i32 {
    unsafe { ffi::Rust_add__SWIG_1(a, b, c) }
}

pub fn add_f64_f64(a: f64, b: f64) -> f64 {
    unsafe { ffi::Rust_add__SWIG_2(a, b) }
}

