// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_1() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Bar_foo__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_Bar_foo__SWIG_1(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_1(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_Bar_foo__SWIG_2() -> c_int;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_2() -> c_int;
    }

    extern "C" {
        pub fn Rust_Bar_num_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_Bar_num_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_Bar__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_foo__SWIG_0() -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_1(jarg1: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_2(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_3(jarg1: *mut c_char) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_4(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_5(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_6(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_7(jarg1: *mut c_void, jarg2: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_foo__SWIG_8(jarg1: c_double, jarg2: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_blah__SWIG_0(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_blah__SWIG_1(jarg1: *mut c_char) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_2(jarg1: c_double) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_3(jarg1: *mut c_char) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_4(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_5(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_6(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Spam_type_get__SWIG_0(jarg1: *mut c_void) -> *const c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_1(jarg1: *mut c_void, jarg2: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_2(jarg1: *mut c_void, jarg2: *mut c_char) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_3(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_4(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_foo__SWIG_5(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_0(jarg1: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_0(jarg1: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_1(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_1(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_2(jarg1: *mut c_char) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_2(jarg1: *mut c_char) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_3(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_3(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_4(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_4(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_bar__SWIG_5(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_bar__SWIG_5(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_delete_Spam__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_fbool__SWIG_0(jarg1: c_uchar) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_fbool__SWIG_1(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_fint__SWIG_0(jarg1: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_fdouble__SWIG_0(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_num__SWIG_0(jarg1: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_num__SWIG_1(jarg1: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_fid__SWIG_0(jarg1: c_int, jarg2: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_fid__SWIG_1(jarg1: c_int, jarg2: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_fid__SWIG_2(jarg1: c_double, jarg2: c_int) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_fid__SWIG_3(jarg1: c_double, jarg2: c_double) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_sizeof_long__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_as_ul__SWIG_0() -> c_ulong;
    }

    extern "C" {
        pub fn Rust_as_ul__SWIG_1(jarg1: c_ulong) -> c_ulong;
    }

    extern "C" {
        pub fn Rust_as_l__SWIG_0() -> c_long;
    }

    extern "C" {
        pub fn Rust_as_l__SWIG_1(jarg1: c_long) -> c_long;
    }

    extern "C" {
        pub fn Rust_as_ull__SWIG_0() -> c_ulonglong;
    }

    extern "C" {
        pub fn Rust_as_ull__SWIG_1(jarg1: c_ulonglong) -> c_ulonglong;
    }

    extern "C" {
        pub fn Rust_as_ll__SWIG_0() -> c_longlong;
    }

    extern "C" {
        pub fn Rust_as_ll__SWIG_1(jarg1: c_longlong) -> c_longlong;
    }

    extern "C" {
        pub fn Rust_malloc_void__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_free_void__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_ClassA__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_ClassA_method1__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_ClassA_method1__SWIG_1(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_ClassA__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_int_object__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_int_object__SWIG_1(jarg1: c_int) -> c_int;
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
}

/// Rust wrapper for C++ class Bar
/// Holds a pointer to the underlying C++ object.
pub struct Bar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bar
pub trait BarTrait {
    fn foo_int_int(&mut self, a: i32, b: i32) -> i32;
    fn foo_int(&mut self, a: i32) -> i32;
    fn foo(&mut self) -> i32;
}

impl Bar {
    pub fn new_int(i: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_0(i) },
        }
    }
}

impl Bar {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_1() },
        }
    }
}

impl Bar {
    pub fn Bar_foo_int_int(a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_Bar_foo__SWIG_0(a, b) }
    }
}

impl Bar {
    pub fn foo_int_int(a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_foo__SWIG_0(a, b) }
    }
}

impl Bar {
    pub fn Bar_foo_int(a: i32) -> i32 {
        unsafe { ffi::Rust_Bar_foo__SWIG_1(a) }
    }
}

impl Bar {
    pub fn foo_int(a: i32) -> i32 {
        unsafe { ffi::Rust_foo__SWIG_1(a) }
    }
}

impl Bar {
    pub fn Bar_foo() -> i32 {
        unsafe { ffi::Rust_Bar_foo__SWIG_2() }
    }
}

impl Bar {
    pub fn foo() -> i32 {
        unsafe { ffi::Rust_foo__SWIG_2() }
    }
}

impl Bar {
    pub fn set_num(&self, num: i32) {
        unsafe { ffi::Rust_Bar_num_set__SWIG_0(self.ptr, num) }
    }
}

impl Bar {
    pub fn num(&self) -> i32 {
        unsafe { ffi::Rust_Bar_num_get__SWIG_0(self.ptr) }
    }
}

impl Drop for Bar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bar__SWIG_0(self.ptr) }
    }
}

impl Bar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BarTrait for Bar {
    fn foo_int_int(&mut self, a: i32, b: i32) -> i32 {
        unsafe { ffi::Rust_foo__SWIG_0(self.ptr, a, b) }
    }
    fn foo_int(&mut self, a: i32) -> i32 {
        unsafe { ffi::Rust_foo__SWIG_1(self.ptr, a) }
    }
    fn foo(&mut self) -> i32 {
        unsafe { ffi::Rust_foo__SWIG_2(self.ptr) }
    }
}

pub fn foo() -> String {
    unsafe { ffi::Rust_foo__SWIG_0() }
}

pub fn foo_int(arg1: i32) -> String {
    unsafe { ffi::Rust_foo__SWIG_1(arg1) }
}

pub fn foo_f64(arg1: f64) -> String {
    unsafe { ffi::Rust_foo__SWIG_2(arg1) }
}

pub fn foo_f64_Bar(arg1: f64, arg2: *mut c_void) -> String {
    unsafe { ffi::Rust_foo__SWIG_8(arg1, arg2) }
}

pub fn blah_f64(arg1: f64) -> String {
    unsafe { ffi::Rust_blah__SWIG_0(arg1) }
}

/// Rust wrapper for C++ class Spam
/// Holds a pointer to the underlying C++ object.
pub struct Spam {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Spam
pub trait SpamTrait {
    fn foo_int(&mut self, arg0: i32) -> c_char;
    fn foo_f64(&mut self, arg0: f64) -> c_char;
    fn foo_str(&mut self, arg0: *mut c_void) -> c_char;
    fn foo_Foo(&mut self, arg0: *mut c_void) -> c_char;
    fn foo_Bar(&mut self, arg0: *mut c_void) -> c_char;
    fn foo_void(&mut self, arg0: *mut c_void) -> c_char;
    fn bar_int(&mut self, arg0: i32) -> c_char;
    fn bar_f64(&mut self, arg0: f64) -> c_char;
    fn bar_str(&mut self, arg0: *mut c_void) -> c_char;
    fn bar_Foo(&mut self, arg0: *mut c_void) -> c_char;
    fn bar_Bar(&mut self, arg0: *mut c_void) -> c_char;
    fn bar_void(&mut self, arg0: *mut c_void) -> c_char;
}

impl Spam {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_0() },
        }
    }
}

impl Spam {
    pub fn new_int(arg0: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_1(arg0) },
        }
    }
}

impl Spam {
    pub fn new_f64(arg0: f64) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_2(arg0) },
        }
    }
}

impl Spam {
    pub fn new_str(arg0: *mut c_void) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_3(arg0) },
        }
    }
}

impl Spam {
    pub fn new_Foo(arg0: *mut c_void) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_4(arg0) },
        }
    }
}

impl Spam {
    pub fn new_Bar(arg0: *mut c_void) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_5(arg0) },
        }
    }
}

impl Spam {
    pub fn new_void(arg0: *mut c_void) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_6(arg0) },
        }
    }
}

impl Spam {
    pub fn type(&self) -> &str {
        unsafe { ffi::Rust_Spam_type_get__SWIG_0(self.ptr) }
    }
}

impl Spam {
    pub fn Spam_bar_int(arg1: i32) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_0(arg1) }
    }
}

impl Spam {
    pub fn bar_int(arg1: i32) -> String {
        unsafe { ffi::Rust_bar__SWIG_0(arg1) }
    }
}

impl Spam {
    pub fn Spam_bar_f64(arg1: f64) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_1(arg1) }
    }
}

impl Spam {
    pub fn bar_f64(arg1: f64) -> String {
        unsafe { ffi::Rust_bar__SWIG_1(arg1) }
    }
}

impl Spam {
    pub fn Spam_bar_str(arg1: String) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_2(arg1) }
    }
}

impl Spam {
    pub fn bar_str(arg1: String) -> String {
        unsafe { ffi::Rust_bar__SWIG_2(arg1) }
    }
}

impl Spam {
    pub fn Spam_bar_Foo(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_3(arg1) }
    }
}

impl Spam {
    pub fn bar_Foo(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_bar__SWIG_3(arg1) }
    }
}

impl Spam {
    pub fn Spam_bar_Bar(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_4(arg1) }
    }
}

impl Spam {
    pub fn bar_Bar(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_bar__SWIG_4(arg1) }
    }
}

impl Spam {
    pub fn Spam_bar_void(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_Spam_bar__SWIG_5(arg1) }
    }
}

impl Spam {
    pub fn bar_void(arg1: *mut c_void) -> String {
        unsafe { ffi::Rust_bar__SWIG_5(arg1) }
    }
}

impl Drop for Spam {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Spam__SWIG_0(self.ptr) }
    }
}

impl Spam {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl SpamTrait for Spam {
    fn foo_int(&mut self, arg: i32) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_0(self.ptr, arg) }
    }
    fn foo_f64(&mut self, arg: f64) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_1(self.ptr, arg) }
    }
    fn foo_str(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_2(self.ptr, arg) }
    }
    fn foo_Foo(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_3(self.ptr, arg) }
    }
    fn foo_Bar(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_4(self.ptr, arg) }
    }
    fn foo_void(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_Spam_foo__SWIG_5(self.ptr, arg) }
    }
    fn bar_int(&mut self, arg: i32) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_0(self.ptr, arg) }
    }
    fn bar_f64(&mut self, arg: f64) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_1(self.ptr, arg) }
    }
    fn bar_str(&mut self, arg: String) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_2(self.ptr, arg) }
    }
    fn bar_Foo(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_3(self.ptr, arg) }
    }
    fn bar_Bar(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_4(self.ptr, arg) }
    }
    fn bar_void(&mut self, arg: *mut c_void) -> c_char {
        unsafe { ffi::Rust_bar__SWIG_5(self.ptr, arg) }
    }
}

pub fn fbool_bool(b: bool) -> bool {
    unsafe { ffi::Rust_fbool__SWIG_0(b) }
}

pub fn fbool_int(b: i32) -> i32 {
    unsafe { ffi::Rust_fbool__SWIG_1(b) }
}

pub fn fint_int(arg1: i32) -> String {
    unsafe { ffi::Rust_fint__SWIG_0(arg1) }
}

pub fn fdouble_f64(arg1: f64) -> String {
    unsafe { ffi::Rust_fdouble__SWIG_0(arg1) }
}

pub fn num_int(arg1: i32) -> String {
    unsafe { ffi::Rust_num__SWIG_0(arg1) }
}

pub fn num_f64(arg1: f64) -> String {
    unsafe { ffi::Rust_num__SWIG_1(arg1) }
}

pub fn fid_int_int(arg1: i32, arg2: i32) -> String {
    unsafe { ffi::Rust_fid__SWIG_0(arg1, arg2) }
}

pub fn fid_int_f64(arg1: i32, arg2: f64) -> String {
    unsafe { ffi::Rust_fid__SWIG_1(arg1, arg2) }
}

pub fn fid_f64_int(arg1: f64, arg2: i32) -> String {
    unsafe { ffi::Rust_fid__SWIG_2(arg1, arg2) }
}

pub fn fid_f64_f64(arg1: f64, arg2: f64) -> String {
    unsafe { ffi::Rust_fid__SWIG_3(arg1, arg2) }
}

pub fn sizeof_long() -> i32 {
    unsafe { ffi::Rust_sizeof_long__SWIG_0() }
}

pub fn as_ul() -> u64 {
    unsafe { ffi::Rust_as_ul__SWIG_0() }
}

pub fn as_ul_long(ul: u64) -> u64 {
    unsafe { ffi::Rust_as_ul__SWIG_1(ul) }
}

pub fn as_l() -> i64 {
    unsafe { ffi::Rust_as_l__SWIG_0() }
}

pub fn as_l_long(l: i64) -> i64 {
    unsafe { ffi::Rust_as_l__SWIG_1(l) }
}

pub fn as_ull() -> u64 {
    unsafe { ffi::Rust_as_ull__SWIG_0() }
}

pub fn as_ull_long(ull: u64) -> u64 {
    unsafe { ffi::Rust_as_ull__SWIG_1(ull) }
}

pub fn as_ll() -> i64 {
    unsafe { ffi::Rust_as_ll__SWIG_0() }
}

pub fn as_ll_long(ll: i64) -> i64 {
    unsafe { ffi::Rust_as_ll__SWIG_1(ll) }
}

pub fn malloc_void_int(nbytes: i32) -> *mut c_void {
    unsafe { ffi::Rust_malloc_void__SWIG_0(nbytes) }
}

/// Rust wrapper for C++ class ClassA
/// Holds a pointer to the underlying C++ object.
pub struct ClassA {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class ClassA
pub trait ClassATrait {
    fn method1(&mut self) -> i32;
    fn method1_int(&mut self, arg1: i32) -> i32;
    fn method1_int_int(&mut self, arg1: i32, arg2: i32) -> i32;
}

impl ClassA {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_ClassA__SWIG_0() },
        }
    }
}

impl Drop for ClassA {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_ClassA__SWIG_0(self.ptr) }
    }
}

impl ClassA {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl ClassATrait for ClassA {
    fn method1(&mut self) -> i32 {
        unsafe { ffi::Rust_ClassA_method1__SWIG_0(self.ptr) }
    }
    fn method1_int(&mut self, arg1: i32) -> i32 {
        unsafe { ffi::Rust_ClassA_method1__SWIG_1(self.ptr, arg1) }
    }
    fn method1_int_int(&mut self, arg1: i32, arg2: i32) -> i32 {
        unsafe { ffi::Rust_method1(self.ptr, arg1, arg2) }
    }
}

pub fn int_object_int(c: i32) -> i32 {
    unsafe { ffi::Rust_int_object__SWIG_1(c) }
}

