// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_value__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_ValueClass__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_ValueClass__SWIG_1() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_ValueClass_get__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_ValueClass_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_delete_ValueClass__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_set_via_pointer__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_get_via_pointer__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_set_via_ref__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_get_via_ref__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_create_value__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_destroy_value__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_ptr__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_PointerHolder__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_PointerHolder__SWIG_1(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_PointerHolder_set_ptr__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_PointerHolder_get_ptr__SWIG_0(jarg1: *const c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_PointerHolder_get_value__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_PointerHolder__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class ValueClass
/// Holds a pointer to the underlying C++ object.
pub struct ValueClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class ValueClass
pub trait ValueClassTrait {
    fn get(&self) -> i32;
    fn set(&mut self, v: i32);
}

impl ValueClass {
    pub fn new_int() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_ValueClass__SWIG_0() },
        }
    }
}

impl ValueClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_ValueClass__SWIG_1() },
        }
    }
}

impl Drop for ValueClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_ValueClass__SWIG_0(self.ptr) }
    }
}

impl ValueClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl ValueClassTrait for ValueClass {
    fn get(&mut self) -> i32 {
        unsafe { ffi::Rust_ValueClass_get__SWIG_0(self.ptr) }
    }
    fn set(&mut self, v: i32) {
        unsafe { ffi::Rust_ValueClass_set__SWIG_0(self.ptr, v) }
    }
}

pub fn create_value_int(v: i32) -> *mut c_void {
    unsafe { ffi::Rust_create_value__SWIG_0(v) }
}

/// Rust wrapper for C++ class PointerHolder
/// Holds a pointer to the underlying C++ object.
pub struct PointerHolder {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class PointerHolder
pub trait PointerHolderTrait {
    fn set_ptr(&mut self);
    fn get_ptr(&self) -> ValueClass *;
    fn get_value(&self) -> i32;
}

impl PointerHolder {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_PointerHolder__SWIG_0() },
        }
    }
}

impl PointerHolder {
    pub fn new_ValueClass() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_PointerHolder__SWIG_1() },
        }
    }
}

impl Drop for PointerHolder {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_PointerHolder__SWIG_0(self.ptr) }
    }
}

impl PointerHolder {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl PointerHolderTrait for PointerHolder {
    fn set_ptr(&mut self, p: *mut c_void) {
        unsafe { ffi::Rust_PointerHolder_set_ptr__SWIG_0(self.ptr, p) }
    }
    fn get_ptr(&mut self) -> ValueClass * {
        unsafe { ffi::Rust_PointerHolder_get_ptr__SWIG_0(self.ptr) }
    }
    fn get_value(&mut self) -> i32 {
        unsafe { ffi::Rust_PointerHolder_get_value__SWIG_0(self.ptr) }
    }
}

