// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_test_bool__SWIG_0(jarg1: c_uchar) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_test_schar__SWIG_0(jarg1: c_schar) -> c_schar;
    }

    extern "C" {
        pub fn Rust_test_uchar__SWIG_0(jarg1: c_uchar) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_test_short__SWIG_0(jarg1: c_short) -> c_short;
    }

    extern "C" {
        pub fn Rust_test_ushort__SWIG_0(jarg1: c_ushort) -> c_ushort;
    }

    extern "C" {
        pub fn Rust_test_int__SWIG_0(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_test_uint__SWIG_0(jarg1: c_uint) -> c_uint;
    }

    extern "C" {
        pub fn Rust_test_long__SWIG_0(jarg1: c_long) -> c_long;
    }

    extern "C" {
        pub fn Rust_test_ulong__SWIG_0(jarg1: c_ulong) -> c_ulong;
    }

    extern "C" {
        pub fn Rust_test_llong__SWIG_0(jarg1: c_longlong) -> c_longlong;
    }

    extern "C" {
        pub fn Rust_test_ullong__SWIG_0(jarg1: c_ulonglong) -> c_ulonglong;
    }

    extern "C" {
        pub fn Rust_test_float__SWIG_0(jarg1: c_float) -> c_float;
    }

    extern "C" {
        pub fn Rust_test_double__SWIG_0(jarg1: c_double) -> c_double;
    }

    extern "C" {
        pub fn Rust_test_size_t__SWIG_0(jarg1: usize) -> usize;
    }

    extern "C" {
        pub fn Rust_test_ptrdiff_t__SWIG_0(jarg1: isize) -> isize;
    }

    extern "C" {
        pub fn Rust_test_void_ptr__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_test_int_ptr__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_test_char__SWIG_0(jarg1: c_char) -> c_char;
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn test_bool_bool(b: bool) -> bool {
    unsafe { ffi::Rust_test_bool__SWIG_0(b as u8) != 0 }
}

pub fn test_schar_str(c: i8) -> i8 {
    unsafe { ffi::Rust_test_schar__SWIG_0(c) }
}

pub fn test_uchar_str(c: u8) -> u8 {
    unsafe { ffi::Rust_test_uchar__SWIG_0(c) }
}

pub fn test_short_short(s: i16) -> i16 {
    unsafe { ffi::Rust_test_short__SWIG_0(s) }
}

pub fn test_ushort_unsigned_short(s: u16) -> u16 {
    unsafe { ffi::Rust_test_ushort__SWIG_0(s) }
}

pub fn test_int_int(i: i32) -> i32 {
    unsafe { ffi::Rust_test_int__SWIG_0(i) }
}

pub fn test_uint_int(i: u32) -> u32 {
    unsafe { ffi::Rust_test_uint__SWIG_0(i) }
}

pub fn test_long_long(l: c_long) -> c_long {
    unsafe { ffi::Rust_test_long__SWIG_0(l) }
}

pub fn test_ulong_long(l: c_ulong) -> c_ulong {
    unsafe { ffi::Rust_test_ulong__SWIG_0(l) }
}

pub fn test_llong_long(l: i64) -> i64 {
    unsafe { ffi::Rust_test_llong__SWIG_0(l) }
}

pub fn test_ullong_long(l: u64) -> u64 {
    unsafe { ffi::Rust_test_ullong__SWIG_0(l) }
}

pub fn test_float_f32(f: f32) -> f32 {
    unsafe { ffi::Rust_test_float__SWIG_0(f) }
}

pub fn test_double_f64(d: f64) -> f64 {
    unsafe { ffi::Rust_test_double__SWIG_0(d) }
}

pub fn test_size_t_size_t(s: usize) -> usize {
    unsafe { ffi::Rust_test_size_t__SWIG_0(s) }
}

pub fn test_ptrdiff_t_ptrdiff_t(p: isize) -> isize {
    unsafe { ffi::Rust_test_ptrdiff_t__SWIG_0(p) }
}

pub fn test_char_str(c: c_char) -> c_char {
    unsafe { ffi::Rust_test_char__SWIG_0(c) }
}

