/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_primitive_types_WRAP_H_
#define SWIG_primitive_types_WRAP_H_

class SwigDirector_TestDirector : public TestDirector, public Swig::Director {
public:
    SwigDirector_TestDirector();
    virtual ~SwigDirector_TestDirector();
    virtual char const * vval_namet(namet x) override;

// Rust callback for SwigDirector_TestDirector::vval_namet
extern "C" bool SwigDirector_TestDirector_vval_namet_callback(void *director, char const * *result, namet x);

    virtual char const * vval_cnamet(namet const x) override;

// Rust callback for SwigDirector_TestDirector::vval_cnamet
extern "C" bool SwigDirector_TestDirector_vval_cnamet_callback(void *director, char const * *result, namet const x);

    virtual bool vval_bool(bool x) override;

// Rust callback for SwigDirector_TestDirector::vval_bool
extern "C" bool SwigDirector_TestDirector_vval_bool_callback(void *director, bool *result, bool x);

    virtual signed char vval_schar(signed char x) override;

// Rust callback for SwigDirector_TestDirector::vval_schar
extern "C" bool SwigDirector_TestDirector_vval_schar_callback(void *director, signed char *result, signed char x);

    virtual unsigned char vval_uchar(unsigned char x) override;

// Rust callback for SwigDirector_TestDirector::vval_uchar
extern "C" bool SwigDirector_TestDirector_vval_uchar_callback(void *director, unsigned char *result, unsigned char x);

    virtual int vval_int(int x) override;

// Rust callback for SwigDirector_TestDirector::vval_int
extern "C" bool SwigDirector_TestDirector_vval_int_callback(void *director, int *result, int x);

    virtual unsigned int vval_uint(unsigned int x) override;

// Rust callback for SwigDirector_TestDirector::vval_uint
extern "C" bool SwigDirector_TestDirector_vval_uint_callback(void *director, unsigned int *result, unsigned int x);

    virtual short vval_short(short x) override;

// Rust callback for SwigDirector_TestDirector::vval_short
extern "C" bool SwigDirector_TestDirector_vval_short_callback(void *director, short *result, short x);

    virtual unsigned short vval_ushort(unsigned short x) override;

// Rust callback for SwigDirector_TestDirector::vval_ushort
extern "C" bool SwigDirector_TestDirector_vval_ushort_callback(void *director, unsigned short *result, unsigned short x);

    virtual long vval_long(long x) override;

// Rust callback for SwigDirector_TestDirector::vval_long
extern "C" bool SwigDirector_TestDirector_vval_long_callback(void *director, long *result, long x);

    virtual unsigned long vval_ulong(unsigned long x) override;

// Rust callback for SwigDirector_TestDirector::vval_ulong
extern "C" bool SwigDirector_TestDirector_vval_ulong_callback(void *director, unsigned long *result, unsigned long x);

    virtual long long vval_llong(long long x) override;

// Rust callback for SwigDirector_TestDirector::vval_llong
extern "C" bool SwigDirector_TestDirector_vval_llong_callback(void *director, long long *result, long long x);

    virtual unsigned long long vval_ullong(unsigned long long x) override;

// Rust callback for SwigDirector_TestDirector::vval_ullong
extern "C" bool SwigDirector_TestDirector_vval_ullong_callback(void *director, unsigned long long *result, unsigned long long x);

    virtual char vval_char(char x) override;

// Rust callback for SwigDirector_TestDirector::vval_char
extern "C" bool SwigDirector_TestDirector_vval_char_callback(void *director, char *result, char x);

    virtual pchar vval_pchar(pchar x) override;

// Rust callback for SwigDirector_TestDirector::vval_pchar
extern "C" bool SwigDirector_TestDirector_vval_pchar_callback(void *director, pchar *result, pchar x);

    virtual pcharc vval_pcharc(pcharc x) override;

// Rust callback for SwigDirector_TestDirector::vval_pcharc
extern "C" bool SwigDirector_TestDirector_vval_pcharc_callback(void *director, pcharc *result, pcharc x);

    virtual pint vval_pint(pint x) override;

// Rust callback for SwigDirector_TestDirector::vval_pint
extern "C" bool SwigDirector_TestDirector_vval_pint_callback(void *director, pint *result, pint x);

    virtual Hello vval_hello(Hello x) override;

// Rust callback for SwigDirector_TestDirector::vval_hello
extern "C" bool SwigDirector_TestDirector_vval_hello_callback(void *director, Hello *result, Hello x);

    virtual MyInt vval_myint(MyInt x) override;

// Rust callback for SwigDirector_TestDirector::vval_myint
extern "C" bool SwigDirector_TestDirector_vval_myint_callback(void *director, MyInt *result, MyInt x);

    virtual Param< int > vval_parami(Param< int > x) override;

// Rust callback for SwigDirector_TestDirector::vval_parami
extern "C" bool SwigDirector_TestDirector_vval_parami_callback(void *director, Param< int > *result, Param< int > x);

    virtual Param< double > vval_paramd(Param< double > x) override;

// Rust callback for SwigDirector_TestDirector::vval_paramd
extern "C" bool SwigDirector_TestDirector_vval_paramd_callback(void *director, Param< double > *result, Param< double > x);

    virtual Param< char > vval_paramc(Param< char > x) override;

// Rust callback for SwigDirector_TestDirector::vval_paramc
extern "C" bool SwigDirector_TestDirector_vval_paramc_callback(void *director, Param< char > *result, Param< char > x);

    virtual size_t vval_sizet(size_t x) override;

// Rust callback for SwigDirector_TestDirector::vval_sizet
extern "C" bool SwigDirector_TestDirector_vval_sizet_callback(void *director, size_t *result, size_t x);

    virtual bool const & vref_bool(bool const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_bool
extern "C" bool SwigDirector_TestDirector_vref_bool_callback(void *director, bool const & *result, bool const & x);

    virtual signed char const & vref_schar(signed char const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_schar
extern "C" bool SwigDirector_TestDirector_vref_schar_callback(void *director, signed char const & *result, signed char const & x);

    virtual unsigned char const & vref_uchar(unsigned char const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_uchar
extern "C" bool SwigDirector_TestDirector_vref_uchar_callback(void *director, unsigned char const & *result, unsigned char const & x);

    virtual int const & vref_int(int const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_int
extern "C" bool SwigDirector_TestDirector_vref_int_callback(void *director, int const & *result, int const & x);

    virtual unsigned int const & vref_uint(unsigned int const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_uint
extern "C" bool SwigDirector_TestDirector_vref_uint_callback(void *director, unsigned int const & *result, unsigned int const & x);

    virtual short const & vref_short(short const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_short
extern "C" bool SwigDirector_TestDirector_vref_short_callback(void *director, short const & *result, short const & x);

    virtual unsigned short const & vref_ushort(unsigned short const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_ushort
extern "C" bool SwigDirector_TestDirector_vref_ushort_callback(void *director, unsigned short const & *result, unsigned short const & x);

    virtual long const & vref_long(long const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_long
extern "C" bool SwigDirector_TestDirector_vref_long_callback(void *director, long const & *result, long const & x);

    virtual unsigned long const & vref_ulong(unsigned long const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_ulong
extern "C" bool SwigDirector_TestDirector_vref_ulong_callback(void *director, unsigned long const & *result, unsigned long const & x);

    virtual long long const & vref_llong(long long const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_llong
extern "C" bool SwigDirector_TestDirector_vref_llong_callback(void *director, long long const & *result, long long const & x);

    virtual unsigned long long const & vref_ullong(unsigned long long const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_ullong
extern "C" bool SwigDirector_TestDirector_vref_ullong_callback(void *director, unsigned long long const & *result, unsigned long long const & x);

    virtual char const & vref_char(char const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_char
extern "C" bool SwigDirector_TestDirector_vref_char_callback(void *director, char const & *result, char const & x);

    virtual pchar const & vref_pchar(pchar const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_pchar
extern "C" bool SwigDirector_TestDirector_vref_pchar_callback(void *director, pchar const & *result, pchar const & x);

    virtual pcharc const & vref_pcharc(pcharc const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_pcharc
extern "C" bool SwigDirector_TestDirector_vref_pcharc_callback(void *director, pcharc const & *result, pcharc const & x);

    virtual pint const & vref_pint(pint const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_pint
extern "C" bool SwigDirector_TestDirector_vref_pint_callback(void *director, pint const & *result, pint const & x);

    virtual Hello const & vref_hello(Hello const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_hello
extern "C" bool SwigDirector_TestDirector_vref_hello_callback(void *director, Hello const & *result, Hello const & x);

    virtual MyInt const & vref_myint(MyInt const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_myint
extern "C" bool SwigDirector_TestDirector_vref_myint_callback(void *director, MyInt const & *result, MyInt const & x);

    virtual Param< int > const & vref_parami(Param< int > const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_parami
extern "C" bool SwigDirector_TestDirector_vref_parami_callback(void *director, Param< int > const & *result, Param< int > const & x);

    virtual Param< double > const & vref_paramd(Param< double > const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_paramd
extern "C" bool SwigDirector_TestDirector_vref_paramd_callback(void *director, Param< double > const & *result, Param< double > const & x);

    virtual Param< char > const & vref_paramc(Param< char > const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_paramc
extern "C" bool SwigDirector_TestDirector_vref_paramc_callback(void *director, Param< char > const & *result, Param< char > const & x);

    virtual size_t const & vref_sizet(size_t const & x) override;

// Rust callback for SwigDirector_TestDirector::vref_sizet
extern "C" bool SwigDirector_TestDirector_vref_sizet_callback(void *director, size_t const & *result, size_t const & x);

    virtual int ovr_val(bool x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, bool x);

    virtual int ovr_ref(bool const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, bool const & x);

    virtual char const * ovr_str(bool x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, bool x);

    virtual int ovr_val(signed char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, signed char x);

    virtual int ovr_ref(signed char const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, signed char const & x);

    virtual char const * ovr_str(signed char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, signed char x);

    virtual int ovr_val(unsigned char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, unsigned char x);

    virtual int ovr_ref(unsigned char const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, unsigned char const & x);

    virtual char const * ovr_str(unsigned char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, unsigned char x);

    virtual int ovr_val(int x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, int x);

    virtual int ovr_ref(int const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, int const & x);

    virtual char const * ovr_str(int x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, int x);

    virtual int ovr_val(unsigned int x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, unsigned int x);

    virtual int ovr_ref(unsigned int const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, unsigned int const & x);

    virtual char const * ovr_str(unsigned int x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, unsigned int x);

    virtual int ovr_val(short x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, short x);

    virtual int ovr_ref(short const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, short const & x);

    virtual char const * ovr_str(short x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, short x);

    virtual int ovr_val(unsigned short x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, unsigned short x);

    virtual int ovr_ref(unsigned short const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, unsigned short const & x);

    virtual char const * ovr_str(unsigned short x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, unsigned short x);

    virtual int ovr_val(long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, long x);

    virtual int ovr_ref(long const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, long const & x);

    virtual char const * ovr_str(long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, long x);

    virtual int ovr_val(unsigned long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, unsigned long x);

    virtual int ovr_ref(unsigned long const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, unsigned long const & x);

    virtual char const * ovr_str(unsigned long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, unsigned long x);

    virtual int ovr_val(long long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, long long x);

    virtual int ovr_ref(long long const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, long long const & x);

    virtual char const * ovr_str(long long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, long long x);

    virtual int ovr_val(unsigned long long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, unsigned long long x);

    virtual int ovr_ref(unsigned long long const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, unsigned long long const & x);

    virtual char const * ovr_str(unsigned long long x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, unsigned long long x);

    virtual int ovr_val(char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, char x);

    virtual int ovr_ref(char const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, char const & x);

    virtual char const * ovr_str(char x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, char x);

    virtual int ovr_val(pchar x) override;

// Rust callback for SwigDirector_TestDirector::ovr_val
extern "C" bool SwigDirector_TestDirector_ovr_val_callback(void *director, int *result, pchar x);

    virtual int ovr_ref(pchar const & x) override;

// Rust callback for SwigDirector_TestDirector::ovr_ref
extern "C" bool SwigDirector_TestDirector_ovr_ref_callback(void *director, int *result, pchar const & x);

    virtual char const * ovr_str(pchar x) override;

// Rust callback for SwigDirector_TestDirector::ovr_str
extern "C" bool SwigDirector_TestDirector_ovr_str_callback(void *director, char const * *result, pchar x);

    virtual Test * vtest(Test * t) const override;

// Rust callback for SwigDirector_TestDirector::vtest
extern "C" bool SwigDirector_TestDirector_vtest_callback(void *director, Test * *result, Test * t);

private:
    void *swig_rust_director_;  // Pointer to Rust trait object
};


#endif
