// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_x__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Foo_getx__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Bar___deref____SWIG_0(jarg1: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Bar__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_x__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_Bar_getx__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
    fn getx(&mut self) -> i32;
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
    fn getx(&mut self) -> i32 {
        unsafe { ffi::Rust_Foo_getx__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Bar
/// Holds a pointer to the underlying C++ object.
pub struct Bar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bar
pub trait BarTrait {
    fn __deref__(&mut self) -> Foo *;
}

impl Bar {
    pub fn new_Foo() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_0() },
        }
    }
}

impl Drop for Bar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bar__SWIG_0(self.ptr) }
    }
}

impl Bar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BarTrait for Bar {
    fn __deref__(&mut self) -> Foo * {
        unsafe { ffi::Rust_Bar___deref____SWIG_0(self.ptr) }
    }
}

