// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_global_int_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_global_int_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_global_double_set__SWIG_0(jarg1: c_double);
    }

    extern "C" {
        pub fn Rust_global_double_get__SWIG_0() -> c_double;
    }

    extern "C" {
        pub fn Rust_global_str_set__SWIG_0(jarg1: *const c_char);
    }

    extern "C" {
        pub fn Rust_global_str_get__SWIG_0() -> *const c_char;
    }

    extern "C" {
        pub fn Rust_get_global_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_set_global_int__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_StaticClass_static_int_set__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_StaticClass_static_int_get__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticClass_static_double_set__SWIG_0(jarg1: c_double);
    }

    extern "C" {
        pub fn Rust_StaticClass_static_double_get__SWIG_0() -> c_double;
    }

    extern "C" {
        pub fn Rust_StaticClass_instance_int_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_StaticClass_instance_int_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_StaticClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_StaticClass__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_StaticClass_get_static_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_get_static_int__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticClass_set_static_int__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_set_static_int__SWIG_0(jarg1: c_int);
    }

    extern "C" {
        pub fn Rust_StaticClass_add_static__SWIG_0(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_add_static__SWIG_0(jarg1: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticClass_get_instance__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_StaticClass_set_instance__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_delete_StaticClass__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn global_int_set_int(global_int: i32) {
    unsafe { ffi::Rust_global_int_set__SWIG_0(global_int) }
}

pub fn global_int_get() -> i32 {
    unsafe { ffi::Rust_global_int_get__SWIG_0() }
}

pub fn global_double_set_f64(global_double: f64) {
    unsafe { ffi::Rust_global_double_set__SWIG_0(global_double) }
}

pub fn global_double_get() -> f64 {
    unsafe { ffi::Rust_global_double_get__SWIG_0() }
}

pub fn global_str_get() -> &str {
    unsafe { ffi::Rust_global_str_get__SWIG_0() }
}

pub fn get_global_int() -> i32 {
    unsafe { ffi::Rust_get_global_int__SWIG_0() }
}

pub fn set_global_int_int(v: i32) {
    unsafe { ffi::Rust_set_global_int__SWIG_0(v) }
}

/// Rust wrapper for C++ class StaticClass
/// Holds a pointer to the underlying C++ object.
pub struct StaticClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StaticClass
pub trait StaticClassTrait {
    fn get_instance(&self) -> i32;
    fn set_instance(&mut self, v: i32);
}

impl StaticClass {
    pub fn StaticClass_static_int_set_int(StaticClass_static_int: i32) {
        unsafe { ffi::Rust_StaticClass_static_int_set__SWIG_0(StaticClass_static_int) }
    }
}

impl StaticClass {
    pub fn StaticClass_static_int_get() -> i32 {
        unsafe { ffi::Rust_StaticClass_static_int_get__SWIG_0() }
    }
}

impl StaticClass {
    pub fn StaticClass_static_double_set_f64(StaticClass_static_double: f64) {
        unsafe { ffi::Rust_StaticClass_static_double_set__SWIG_0(StaticClass_static_double) }
    }
}

impl StaticClass {
    pub fn StaticClass_static_double_get() -> f64 {
        unsafe { ffi::Rust_StaticClass_static_double_get__SWIG_0() }
    }
}

impl StaticClass {
    pub fn set_instance_int(&self, instance_int: i32) {
        unsafe { ffi::Rust_StaticClass_instance_int_set__SWIG_0(self.ptr, instance_int) }
    }
}

impl StaticClass {
    pub fn instance_int(&self) -> i32 {
        unsafe { ffi::Rust_StaticClass_instance_int_get__SWIG_0(self.ptr) }
    }
}

impl StaticClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticClass__SWIG_0() },
        }
    }
}

impl StaticClass {
    pub fn new_int(v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StaticClass__SWIG_1(v) },
        }
    }
}

impl StaticClass {
    pub fn StaticClass_get_static_int() -> i32 {
        unsafe { ffi::Rust_StaticClass_get_static_int__SWIG_0() }
    }
}

impl StaticClass {
    pub fn get_static_int() -> i32 {
        unsafe { ffi::Rust_get_static_int__SWIG_0() }
    }
}

impl StaticClass {
    pub fn StaticClass_set_static_int_int(v: i32) {
        unsafe { ffi::Rust_StaticClass_set_static_int__SWIG_0(v) }
    }
}

impl StaticClass {
    pub fn set_static_int_int(v: i32) {
        unsafe { ffi::Rust_set_static_int__SWIG_0(v) }
    }
}

impl StaticClass {
    pub fn StaticClass_add_static_int(v: i32) -> i32 {
        unsafe { ffi::Rust_StaticClass_add_static__SWIG_0(v) }
    }
}

impl StaticClass {
    pub fn add_static_int(v: i32) -> i32 {
        unsafe { ffi::Rust_add_static__SWIG_0(v) }
    }
}

impl Drop for StaticClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StaticClass__SWIG_0(self.ptr) }
    }
}

impl StaticClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StaticClassTrait for StaticClass {
    fn get_instance(&self) -> i32 {
        unsafe { ffi::Rust_StaticClass_get_instance__SWIG_0(self.ptr) }
    }
    fn set_instance(&mut self, v: i32) {
        unsafe { ffi::Rust_StaticClass_set_instance__SWIG_0(self.ptr, v) }
    }
}

