// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_get_greeting__SWIG_0() -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_echo_string__SWIG_0(jarg1: *const std::ffi::c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_concat_strings__SWIG_0(jarg1: *const std::ffi::c_void, jarg2: *const std::ffi::c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_string_length__SWIG_0(jarg1: *const std::ffi::c_void) -> usize;
    }

    extern "C" {
        pub fn Rust_is_string_empty__SWIG_0(jarg1: *const std::ffi::c_void) -> c_uchar;
    }

    extern "C" {
        pub fn Rust_new_StringHolder__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_StringHolder__SWIG_1(jarg1: *const std::ffi::c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_StringHolder_set_value__SWIG_0(jarg1: *mut c_void, jarg2: *const std::ffi::c_void);
    }

    extern "C" {
        pub fn Rust_StringHolder_get_value__SWIG_0(jarg1: *const c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_StringHolder_append__SWIG_0(jarg1: *mut c_void, jarg2: *const std::ffi::c_void);
    }

    extern "C" {
        pub fn Rust_StringHolder_clear__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_StringHolder_length__SWIG_0(jarg1: *const c_void) -> usize;
    }

    extern "C" {
        pub fn Rust_delete_StringHolder__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions


/// Wrapper for C++ std::string
/// 
/// This type provides a safe wrapper around C++ std::string and supports
/// bidirectional conversion between C++ std::string and Rust's String type.
/// 
/// # Memory Management
/// 
/// SwigString owns the underlying C++ std::string and will free it when dropped.
/// 
/// # Example
/// 
/// ```
/// let s = SwigString::from_str("hello");
/// assert_eq!(s.len(), 5);
/// let rust_str: String = s.into();
/// assert_eq!(rust_str, "hello");
/// ```
pub struct SwigString {
    ptr: *mut std::ffi::c_void,
}

// FFI declarations for SwigString helper functions
mod swig_string_ffi {
    extern "C" {
        pub fn SwigString_new() -> *mut std::ffi::c_void;
        pub fn SwigString_from_bytes(data: *const std::os::raw::c_char, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigString_from_c_str(s: *const std::os::raw::c_char) -> *mut std::ffi::c_void;
        pub fn SwigString_delete(ptr: *mut std::ffi::c_void);
        pub fn SwigString_c_str(ptr: *const std::ffi::c_void) -> *const std::os::raw::c_char;
        pub fn SwigString_data(ptr: *const std::ffi::c_void) -> *const std::os::raw::c_char;
        pub fn SwigString_len(ptr: *const std::ffi::c_void) -> usize;
        pub fn SwigString_is_empty(ptr: *const std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigString_clear(ptr: *mut std::ffi::c_void);
        pub fn SwigString_append(ptr: *mut std::ffi::c_void, data: *const std::os::raw::c_char, len: usize);
        pub fn SwigString_append_c_str(ptr: *mut std::ffi::c_void, s: *const std::os::raw::c_char);
        pub fn SwigString_assign(ptr: *mut std::ffi::c_void, data: *const std::os::raw::c_char, len: usize);
        pub fn SwigString_capacity(ptr: *const std::ffi::c_void) -> usize;
        pub fn SwigString_reserve(ptr: *mut std::ffi::c_void, capacity: usize);
        pub fn SwigString_compare(ptr1: *const std::ffi::c_void, ptr2: *const std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigString_clone(ptr: *const std::ffi::c_void) -> *mut std::ffi::c_void;
        pub fn SwigString_resize(ptr: *mut std::ffi::c_void, new_len: usize, fill_char: std::os::raw::c_char);
        pub fn SwigString_substr(ptr: *const std::ffi::c_void, pos: usize, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigString_find(ptr: *const std::ffi::c_void, needle: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_rfind(ptr: *const std::ffi::c_void, needle: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_push_back(ptr: *mut std::ffi::c_void, c: std::os::raw::c_char);
        pub fn SwigString_pop_back(ptr: *mut std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigString_at(ptr: *const std::ffi::c_void, index: usize) -> std::os::raw::c_char;
        pub fn SwigString_set_at(ptr: *mut std::ffi::c_void, index: usize, c: std::os::raw::c_char);
        // Advanced methods
        pub fn SwigString_insert(ptr: *mut std::ffi::c_void, pos: usize, data: *const std::os::raw::c_char, len: usize);
        pub fn SwigString_insert_char(ptr: *mut std::ffi::c_void, pos: usize, count: usize, c: std::os::raw::c_char);
        pub fn SwigString_erase(ptr: *mut std::ffi::c_void, pos: usize, len: usize);
        pub fn SwigString_replace(ptr: *mut std::ffi::c_void, pos: usize, len: usize, data: *const std::os::raw::c_char, data_len: usize);
        pub fn SwigString_find_first_of(ptr: *const std::ffi::c_void, chars: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_find_last_of(ptr: *const std::ffi::c_void, chars: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_find_first_not_of(ptr: *const std::ffi::c_void, chars: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_find_last_not_of(ptr: *const std::ffi::c_void, chars: *const std::os::raw::c_char, pos: usize) -> std::os::raw::c_long;
        pub fn SwigString_shrink_to_fit(ptr: *mut std::ffi::c_void);
        pub fn SwigString_front(ptr: *const std::ffi::c_void) -> std::os::raw::c_char;
        pub fn SwigString_back(ptr: *const std::ffi::c_void) -> std::os::raw::c_char;
        pub fn SwigString_swap(ptr1: *mut std::ffi::c_void, ptr2: *mut std::ffi::c_void);
    }
}

impl SwigString {
    /// Special value indicating "until end of string" or "not found"
    pub const NPOS: usize = usize::MAX;
    
    /// Create an empty SwigString
    pub fn new() -> Self {
        unsafe {
            Self { ptr: swig_string_ffi::SwigString_new() }
        }
    }
    
    /// Create from a Rust &str
    pub fn from_str(s: &str) -> Self {
        unsafe {
            Self { 
                ptr: swig_string_ffi::SwigString_from_bytes(
                    s.as_ptr() as *const std::os::raw::c_char, 
                    s.len()
                ) 
            }
        }
    }
    
    /// Create from bytes (may not be valid UTF-8)
    pub fn from_bytes(bytes: &[u8]) -> Self {
        unsafe {
            Self { 
                ptr: swig_string_ffi::SwigString_from_bytes(
                    bytes.as_ptr() as *const std::os::raw::c_char, 
                    bytes.len()
                ) 
            }
        }
    }
    
    /// Get as C string pointer (null-terminated)
    pub fn as_c_str(&self) -> *const std::os::raw::c_char {
        unsafe { swig_string_ffi::SwigString_c_str(self.ptr) }
    }
    
    /// Get string length
    pub fn len(&self) -> usize {
        unsafe { swig_string_ffi::SwigString_len(self.ptr) }
    }
    
    /// Check if empty
    pub fn is_empty(&self) -> bool {
        unsafe { swig_string_ffi::SwigString_is_empty(self.ptr) != 0 }
    }
    
    /// Convert to Rust String (owned)
    pub fn into_string(self) -> String {
        let bytes = self.as_bytes();
        let bytes = bytes.to_vec();
        std::mem::forget(self);
        String::from_utf8_lossy(&bytes).into_owned()
    }
    
    /// Convert to Rust String with lossy UTF-8 conversion
    pub fn to_string_lossy(&self) -> String {
        String::from_utf8_lossy(self.as_bytes()).into_owned()
    }
    
    /// Get the bytes as a slice
    pub fn as_bytes(&self) -> &[u8] {
        unsafe {
            let data = swig_string_ffi::SwigString_data(self.ptr);
            let len = swig_string_ffi::SwigString_len(self.ptr);
            if data.is_null() || len == 0 {
                &[]
            } else {
                std::slice::from_raw_parts(data as *const u8, len)
            }
        }
    }
    
    /// Clear the string
    pub fn clear(&mut self) {
        unsafe { swig_string_ffi::SwigString_clear(self.ptr) }
    }
    
    /// Append bytes
    pub fn append(&mut self, bytes: &[u8]) {
        unsafe {
            swig_string_ffi::SwigString_append(
                self.ptr, 
                bytes.as_ptr() as *const std::os::raw::c_char, 
                bytes.len()
            )
        }
    }
    
    /// Append a string
    pub fn append_str(&mut self, s: &str) {
        self.append(s.as_bytes())
    }
    
    /// Get capacity
    pub fn capacity(&self) -> usize {
        unsafe { swig_string_ffi::SwigString_capacity(self.ptr) }
    }
    
    /// Reserve capacity
    pub fn reserve(&mut self, capacity: usize) {
        unsafe { swig_string_ffi::SwigString_reserve(self.ptr, capacity) }
    }
    
    /// Clone the string
    pub fn clone_swig(&self) -> Self {
        unsafe { Self { ptr: swig_string_ffi::SwigString_clone(self.ptr) } }
    }
    
    /// Resize the string
    pub fn resize(&mut self, new_len: usize, fill_char: u8) {
        unsafe { swig_string_ffi::SwigString_resize(self.ptr, new_len, fill_char as std::os::raw::c_char) }
    }
    
    /// Get substring
    pub fn substr(&self, pos: usize, len: usize) -> Self {
        unsafe { Self { ptr: swig_string_ffi::SwigString_substr(self.ptr, pos, len) } }
    }
    
    /// Find substring
    pub fn find(&self, needle: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_find(
                self.ptr, 
                needle.as_ptr() as *const std::os::raw::c_char, 
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Reverse find
    pub fn rfind(&self, needle: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_rfind(
                self.ptr, 
                needle.as_ptr() as *const std::os::raw::c_char, 
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Compare with another SwigString
    pub fn compare(&self, other: &SwigString) -> std::cmp::Ordering {
        unsafe {
            let result = swig_string_ffi::SwigString_compare(self.ptr, other.ptr);
            result.cmp(&0)
        }
    }
    
    // ========================================================================
    // Advanced string methods
    // ========================================================================
    
    /// Insert bytes at position
    pub fn insert(&mut self, pos: usize, bytes: &[u8]) {
        unsafe {
            swig_string_ffi::SwigString_insert(
                self.ptr,
                pos,
                bytes.as_ptr() as *const std::os::raw::c_char,
                bytes.len()
            )
        }
    }
    
    /// Insert a string at position
    pub fn insert_str(&mut self, pos: usize, s: &str) {
        self.insert(pos, s.as_bytes())
    }
    
    /// Insert a character count times at position
    pub fn insert_char(&mut self, pos: usize, count: usize, c: u8) {
        unsafe {
            swig_string_ffi::SwigString_insert_char(self.ptr, pos, count, c as std::os::raw::c_char)
        }
    }
    
    /// Erase characters starting from position
    pub fn erase(&mut self, pos: usize, len: usize) {
        unsafe { swig_string_ffi::SwigString_erase(self.ptr, pos, len) }
    }
    
    /// Replace characters at position with bytes
    pub fn replace(&mut self, pos: usize, len: usize, bytes: &[u8]) {
        unsafe {
            swig_string_ffi::SwigString_replace(
                self.ptr,
                pos,
                len,
                bytes.as_ptr() as *const std::os::raw::c_char,
                bytes.len()
            )
        }
    }
    
    /// Replace characters at position with a string
    pub fn replace_str(&mut self, pos: usize, len: usize, s: &str) {
        self.replace(pos, len, s.as_bytes())
    }
    
    /// Find first occurrence of any character from the set
    pub fn find_first_of(&self, chars: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_find_first_of(
                self.ptr,
                chars.as_ptr() as *const std::os::raw::c_char,
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Find last occurrence of any character from the set
    pub fn find_last_of(&self, chars: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_find_last_of(
                self.ptr,
                chars.as_ptr() as *const std::os::raw::c_char,
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Find first character NOT in the set
    pub fn find_first_not_of(&self, chars: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_find_first_not_of(
                self.ptr,
                chars.as_ptr() as *const std::os::raw::c_char,
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Find last character NOT in the set
    pub fn find_last_not_of(&self, chars: &str, pos: usize) -> Option<usize> {
        unsafe {
            let result = swig_string_ffi::SwigString_find_last_not_of(
                self.ptr,
                chars.as_ptr() as *const std::os::raw::c_char,
                pos
            );
            if result < 0 { None } else { Some(result as usize) }
        }
    }
    
    /// Shrink capacity to fit size
    pub fn shrink_to_fit(&mut self) {
        unsafe { swig_string_ffi::SwigString_shrink_to_fit(self.ptr) }
    }
    
    /// Get front character (first character)
    pub fn front(&self) -> Option<u8> {
        unsafe {
            let c = swig_string_ffi::SwigString_front(self.ptr);
            if c == '\0' as std::os::raw::c_char { None } else { Some(c as u8) }
        }
    }
    
    /// Get back character (last character)
    pub fn back(&self) -> Option<u8> {
        unsafe {
            let c = swig_string_ffi::SwigString_back(self.ptr);
            if c == '\0' as std::os::raw::c_char { None } else { Some(c as u8) }
        }
    }
    
    /// Swap contents with another SwigString
    pub fn swap(&mut self, other: &mut SwigString) {
        unsafe { swig_string_ffi::SwigString_swap(self.ptr, other.ptr) }
    }
}

impl Default for SwigString {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for SwigString {
    fn drop(&mut self) {
        unsafe {
            if !self.ptr.is_null() {
                swig_string_ffi::SwigString_delete(self.ptr);
            }
        }
    }
}

impl Clone for SwigString {
    fn clone(&self) -> Self {
        self.clone_swig()
    }
}

impl std::fmt::Display for SwigString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = self.to_string_lossy();
        write!(f, "{}", s)
    }
}

impl std::fmt::Debug for SwigString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = self.to_string_lossy();
        write!(f, "SwigString({:?})", s)
    }
}

impl PartialEq for SwigString {
    fn eq(&self, other: &Self) -> bool {
        self.compare(other) == std::cmp::Ordering::Equal
    }
}

impl Eq for SwigString {}

impl PartialOrd for SwigString {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for SwigString {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.compare(other)
    }
}

impl std::hash::Hash for SwigString {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.as_bytes().hash(state);
    }
}

impl From<String> for SwigString {
    fn from(s: String) -> Self {
        Self::from_str(&s)
    }
}

impl From<&str> for SwigString {
    fn from(s: &str) -> Self {
        Self::from_str(s)
    }
}

impl From<SwigString> for String {
    fn from(s: SwigString) -> Self {
        s.into_string()
    }
}

impl From<&SwigString> for String {
    fn from(s: &SwigString) -> Self {
        s.to_string_lossy()
    }
}

// Note: Into<String> for SwigString is auto-generated by Rust from From<SwigString> for String

impl std::ops::Deref for SwigString {
    type Target = [u8];
    
    fn deref(&self) -> &Self::Target {
        self.as_bytes()
    }
}

impl std::borrow::Borrow<[u8]> for SwigString {
    fn borrow(&self) -> &[u8] {
        self.as_bytes()
    }
}

pub fn get_greeting() -> SwigString {
    SwigString { ptr: unsafe { ffi::Rust_get_greeting__SWIG_0() } }
}

/// Rust wrapper for C++ class StringHolder
/// Holds a pointer to the underlying C++ object.
pub struct StringHolder {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class StringHolder
pub trait StringHolderTrait {
    fn set_value(&mut self, value: &SwigString);
    fn get_value(&self) -> SwigString;
    fn append(&mut self, s: &SwigString);
    fn clear(&mut self);
    fn length(&self) -> usize;
}

impl StringHolder {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StringHolder__SWIG_0() },
        }
    }
}

impl StringHolder {
    pub fn new_string(value: &SwigString) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_StringHolder__SWIG_1(value.ptr) },
        }
    }
}

impl Drop for StringHolder {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_StringHolder__SWIG_0(self.ptr) }
    }
}

impl StringHolder {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl StringHolderTrait for StringHolder {
    fn set_value(&mut self, value: &SwigString) {
        unsafe { ffi::Rust_StringHolder_set_value__SWIG_0(self.ptr, value.ptr) }
    }
    fn get_value(&self) -> SwigString {
        SwigString { ptr: unsafe { ffi::Rust_StringHolder_get_value__SWIG_0(self.ptr) } }
    }
    fn append(&mut self, s: &SwigString) {
        unsafe { ffi::Rust_StringHolder_append__SWIG_0(self.ptr, s.ptr) }
    }
    fn clear(&mut self) {
        unsafe { ffi::Rust_StringHolder_clear__SWIG_0(self.ptr) }
    }
    fn length(&self) -> usize {
        unsafe { ffi::Rust_StringHolder_length__SWIG_0(self.ptr) }
    }
}

