// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_get_wgreeting__SWIG_0() -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_echo_wstring__SWIG_0(jarg1: *const std::ffi::c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_concat_wstrings__SWIG_0(jarg1: *const std::ffi::c_void, jarg2: *const std::ffi::c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_wstring_length__SWIG_0(jarg1: *const std::ffi::c_void) -> usize;
    }

    extern "C" {
        pub fn Rust_new_WStringHolder__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_WStringHolder__SWIG_1(jarg1: *const std::ffi::c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_WStringHolder_set_value__SWIG_0(jarg1: *mut c_void, jarg2: *const std::ffi::c_void);
    }

    extern "C" {
        pub fn Rust_WStringHolder_get_value__SWIG_0(jarg1: *const c_void) -> *mut std::ffi::c_void;
    }

    extern "C" {
        pub fn Rust_WStringHolder_append__SWIG_0(jarg1: *mut c_void, jarg2: *const std::ffi::c_void);
    }

    extern "C" {
        pub fn Rust_WStringHolder_clear__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_delete_WStringHolder__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_get_wchar__SWIG_0() -> u16;
    }

    extern "C" {
        pub fn Rust_echo_wchar__SWIG_0(jarg1: u16) -> u16;
    }

}

use std::os::raw::*;

// Safe wrapper functions


/// Wrapper for C++ std::wstring
/// 
/// This type provides a safe wrapper around C++ std::wstring.
/// 
/// # Platform Notes
/// 
/// - Windows: wchar_t is 2 bytes (UTF-16)
/// - Unix: wchar_t is 4 bytes (UTF-32)
/// 
/// Use `wchar_size()` to determine the current platform's wchar_t size.
pub struct SwigWString {
    ptr: *mut std::ffi::c_void,
}

// FFI declarations for SwigWString helper functions
mod swig_wstring_ffi {
    extern "C" {
        pub fn SwigWString_new() -> *mut std::ffi::c_void;
        pub fn SwigWString_from_wchars(data: *const std::ffi::c_void, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigWString_from_utf16(data: *const u16, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigWString_from_utf32(data: *const u32, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigWString_delete(ptr: *mut std::ffi::c_void);
        pub fn SwigWString_data(ptr: *const std::ffi::c_void) -> *const std::ffi::c_void;
        pub fn SwigWString_len(ptr: *const std::ffi::c_void) -> usize;
        pub fn SwigWString_is_empty(ptr: *const std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigWString_clear(ptr: *mut std::ffi::c_void);
        pub fn SwigWString_append(ptr: *mut std::ffi::c_void, data: *const std::ffi::c_void, len: usize);
        pub fn SwigWString_append_utf16(ptr: *mut std::ffi::c_void, data: *const u16, len: usize);
        pub fn SwigWString_at(ptr: *const std::ffi::c_void, index: usize) -> u16;
        pub fn SwigWString_set_at(ptr: *mut std::ffi::c_void, index: usize, c: u16);
        pub fn SwigWString_capacity(ptr: *const std::ffi::c_void) -> usize;
        pub fn SwigWString_reserve(ptr: *mut std::ffi::c_void, capacity: usize);
        pub fn SwigWString_compare(ptr1: *const std::ffi::c_void, ptr2: *const std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigWString_clone(ptr: *const std::ffi::c_void) -> *mut std::ffi::c_void;
        pub fn SwigWString_resize(ptr: *mut std::ffi::c_void, new_len: usize, fill_char: u16);
        pub fn SwigWString_substr(ptr: *const std::ffi::c_void, pos: usize, len: usize) -> *mut std::ffi::c_void;
        pub fn SwigWString_find(ptr: *const std::ffi::c_void, needle: *const std::ffi::c_void, pos: usize) -> std::os::raw::c_long;
        pub fn SwigWString_rfind(ptr: *const std::ffi::c_void, needle: *const std::ffi::c_void, pos: usize) -> std::os::raw::c_long;
        pub fn SwigWString_push_back(ptr: *mut std::ffi::c_void, c: u16);
        pub fn SwigWString_pop_back(ptr: *mut std::ffi::c_void) -> std::os::raw::c_int;
        pub fn SwigWString_insert(ptr: *mut std::ffi::c_void, pos: usize, data: *const std::ffi::c_void, len: usize);
        pub fn SwigWString_erase(ptr: *mut std::ffi::c_void, pos: usize, len: usize);
        pub fn SwigWString_replace(ptr: *mut std::ffi::c_void, pos: usize, len: usize, data: *const std::ffi::c_void, data_len: usize);
        pub fn SwigWString_find_first_of(ptr: *const std::ffi::c_void, chars: *const std::ffi::c_void, pos: usize) -> std::os::raw::c_long;
        pub fn SwigWString_find_last_of(ptr: *const std::ffi::c_void, chars: *const std::ffi::c_void, pos: usize) -> std::os::raw::c_long;
        pub fn SwigWString_shrink_to_fit(ptr: *mut std::ffi::c_void);
        pub fn SwigWString_front(ptr: *const std::ffi::c_void) -> u16;
        pub fn SwigWString_back(ptr: *const std::ffi::c_void) -> u16;
        pub fn SwigWString_swap(ptr1: *mut std::ffi::c_void, ptr2: *mut std::ffi::c_void);
        pub fn SwigWString_wchar_size() -> usize;
    }
}

impl SwigWString {
    /// Size of wchar_t on the current platform
    /// - 2 on Windows (UTF-16)
    /// - 4 on Unix (UTF-32)
    pub fn wchar_size() -> usize {
        unsafe { swig_wstring_ffi::SwigWString_wchar_size() }
    }
    
    /// Create an empty SwigWString
    pub fn new() -> Self {
        unsafe {
            Self { ptr: swig_wstring_ffi::SwigWString_new() }
        }
    }
    
    /// Create from UTF-16 data
    /// This is the preferred way on Windows where wchar_t = u16
    pub fn from_utf16(data: &[u16]) -> Self {
        unsafe {
            Self { 
                ptr: swig_wstring_ffi::SwigWString_from_utf16(data.as_ptr(), data.len())
            }
        }
    }
    
    /// Create from UTF-32 data
    /// This is the preferred way on Unix where wchar_t = u32
    pub fn from_utf32(data: &[u32]) -> Self {
        unsafe {
            Self { 
                ptr: swig_wstring_ffi::SwigWString_from_utf32(data.as_ptr(), data.len())
            }
        }
    }
    
    /// Get string length (number of wchar_t characters)
    pub fn len(&self) -> usize {
        unsafe { swig_wstring_ffi::SwigWString_len(self.ptr) }
    }
    
    /// Check if empty
    pub fn is_empty(&self) -> bool {
        unsafe { swig_wstring_ffi::SwigWString_is_empty(self.ptr) != 0 }
    }
    
    /// Get the data as a slice of u16 (for Windows/UTF-16)
    /// # Safety
    /// This is only valid on platforms where wchar_t is 2 bytes
    pub unsafe fn as_u16_slice(&self) -> &[u16] {
        let data = swig_wstring_ffi::SwigWString_data(self.ptr) as *const u16;
        let len = swig_wstring_ffi::SwigWString_len(self.ptr);
        if data.is_null() || len == 0 {
            &[]
        } else {
            std::slice::from_raw_parts(data, len)
        }
    }
    
    /// Get the data as a slice of u32 (for Unix/UTF-32)
    /// # Safety
    /// This is only valid on platforms where wchar_t is 4 bytes
    pub unsafe fn as_u32_slice(&self) -> &[u32] {
        let data = swig_wstring_ffi::SwigWString_data(self.ptr) as *const u32;
        let len = swig_wstring_ffi::SwigWString_len(self.ptr);
        if data.is_null() || len == 0 {
            &[]
        } else {
            std::slice::from_raw_parts(data, len)
        }
    }
    
    /// Clear the string
    pub fn clear(&mut self) {
        unsafe { swig_wstring_ffi::SwigWString_clear(self.ptr) }
    }
    
    /// Append UTF-16 data
    pub fn append_utf16(&mut self, data: &[u16]) {
        unsafe {
            swig_wstring_ffi::SwigWString_append_utf16(self.ptr, data.as_ptr(), data.len())
        }
    }
    
    /// Get capacity
    pub fn capacity(&self) -> usize {
        unsafe { swig_wstring_ffi::SwigWString_capacity(self.ptr) }
    }
    
    /// Reserve capacity
    pub fn reserve(&mut self, capacity: usize) {
        unsafe { swig_wstring_ffi::SwigWString_reserve(self.ptr, capacity) }
    }
    
    /// Clone the string
    pub fn clone_wstring(&self) -> Self {
        unsafe { Self { ptr: swig_wstring_ffi::SwigWString_clone(self.ptr) } }
    }
    
    /// Resize the string
    pub fn resize(&mut self, new_len: usize, fill_char: u16) {
        unsafe { swig_wstring_ffi::SwigWString_resize(self.ptr, new_len, fill_char) }
    }
    
    /// Get substring
    pub fn substr(&self, pos: usize, len: usize) -> Self {
        unsafe { Self { ptr: swig_wstring_ffi::SwigWString_substr(self.ptr, pos, len) } }
    }
    
    /// Compare with another SwigWString
    pub fn compare(&self, other: &SwigWString) -> std::cmp::Ordering {
        unsafe {
            let result = swig_wstring_ffi::SwigWString_compare(self.ptr, other.ptr);
            result.cmp(&0)
        }
    }
    
    /// Erase characters starting from position
    pub fn erase(&mut self, pos: usize, len: usize) {
        unsafe { swig_wstring_ffi::SwigWString_erase(self.ptr, pos, len) }
    }
    
    /// Shrink capacity to fit size
    pub fn shrink_to_fit(&mut self) {
        unsafe { swig_wstring_ffi::SwigWString_shrink_to_fit(self.ptr) }
    }
    
    /// Swap contents with another SwigWString
    pub fn swap(&mut self, other: &mut SwigWString) {
        unsafe { swig_wstring_ffi::SwigWString_swap(self.ptr, other.ptr) }
    }
}

impl Default for SwigWString {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for SwigWString {
    fn drop(&mut self) {
        unsafe {
            if !self.ptr.is_null() {
                swig_wstring_ffi::SwigWString_delete(self.ptr);
            }
        }
    }
}

impl Clone for SwigWString {
    fn clone(&self) -> Self {
        self.clone_wstring()
    }
}

impl std::fmt::Debug for SwigWString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SwigWString(len={}, wchar_size={})", self.len(), Self::wchar_size())
    }
}

impl PartialEq for SwigWString {
    fn eq(&self, other: &Self) -> bool {
        self.compare(other) == std::cmp::Ordering::Equal
    }
}

impl Eq for SwigWString {}

impl PartialOrd for SwigWString {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for SwigWString {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.compare(other)
    }
}

pub fn get_wgreeting() -> SwigWString {
    SwigWString { ptr: unsafe { ffi::Rust_get_wgreeting__SWIG_0() } }
}

pub fn get_wchar() -> u16 {
    unsafe { ffi::Rust_get_wchar__SWIG_0() }
}

pub fn echo_wchar_str(c: u16) -> u16 {
    unsafe { ffi::Rust_echo_wchar__SWIG_0(c) }
}

/// Rust wrapper for C++ class WStringHolder
/// Holds a pointer to the underlying C++ object.
pub struct WStringHolder {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class WStringHolder
pub trait WStringHolderTrait {
    fn set_value(&mut self, value: &SwigWString);
    fn get_value(&self) -> SwigWString;
    fn append(&mut self, s: &SwigWString);
    fn clear(&mut self);
}

impl WStringHolder {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_WStringHolder__SWIG_0() },
        }
    }
}

impl WStringHolder {
    pub fn new_std_wstring(value: &SwigWString) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_WStringHolder__SWIG_1(value.ptr) },
        }
    }
}

impl Drop for WStringHolder {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_WStringHolder__SWIG_0(self.ptr) }
    }
}

impl WStringHolder {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl WStringHolderTrait for WStringHolder {
    fn set_value(&mut self, value: &SwigWString) {
        unsafe { ffi::Rust_WStringHolder_set_value__SWIG_0(self.ptr, value.ptr) }
    }
    fn get_value(&self) -> SwigWString {
        SwigWString { ptr: unsafe { ffi::Rust_WStringHolder_get_value__SWIG_0(self.ptr) } }
    }
    fn append(&mut self, s: &SwigWString) {
        unsafe { ffi::Rust_WStringHolder_append__SWIG_0(self.ptr, s.ptr) }
    }
    fn clear(&mut self) {
        unsafe { ffi::Rust_WStringHolder_clear__SWIG_0(self.ptr) }
    }
}

