// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_Foo_x_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_Foo_x_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Bar_a_set__SWIG_0(jarg1: *mut c_void, jarg2: *const c_void);
    }

    extern "C" {
        pub fn Rust_Bar_a_get__SWIG_0(jarg1: *mut c_void) -> *const c_void;
    }

    extern "C" {
        pub fn Rust_Bar_b_set__SWIG_0(jarg1: *mut c_void, jarg2: *const c_void);
    }

    extern "C" {
        pub fn Rust_Bar_b_get__SWIG_0(jarg1: *mut c_void) -> *const c_void;
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Bar__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
}

impl Foo {
    pub fn set_x(&self, x: i32) {
        unsafe { ffi::Rust_Foo_x_set__SWIG_0(self.ptr, x) }
    }
}

impl Foo {
    pub fn x(&self) -> i32 {
        unsafe { ffi::Rust_Foo_x_get__SWIG_0(self.ptr) }
    }
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
}

/// Rust wrapper for C++ class Bar
/// Holds a pointer to the underlying C++ object.
pub struct Bar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bar
pub trait BarTrait {
}

impl Bar {
    pub fn set_a(&self, a: &$*1_type) {
        unsafe { ffi::Rust_Bar_a_set__SWIG_0(self.ptr, a) }
    }
}

impl Bar {
    pub fn a(&self) -> &$*1_type {
        unsafe { ffi::Rust_Bar_a_get__SWIG_0(self.ptr) }
    }
}

impl Bar {
    pub fn set_b(&self, b: &$*1_type) {
        unsafe { ffi::Rust_Bar_b_set__SWIG_0(self.ptr, b) }
    }
}

impl Bar {
    pub fn b(&self) -> &$*1_type {
        unsafe { ffi::Rust_Bar_b_get__SWIG_0(self.ptr) }
    }
}

impl Bar {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_0() },
        }
    }
}

impl Drop for Bar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bar__SWIG_0(self.ptr) }
    }
}

impl Bar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BarTrait for Bar {
}

