// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_IntContainer_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_IntContainer_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_IntContainer__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_IntContainer__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_IntContainer_get__SWIG_0(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_IntContainer_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_IntContainer_add__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_IntContainer__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_DoubleContainer_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_double);
    }

    extern "C" {
        pub fn Rust_DoubleContainer_value_get__SWIG_0(jarg1: *mut c_void) -> c_double;
    }

    extern "C" {
        pub fn Rust_new_DoubleContainer__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_DoubleContainer__SWIG_1(jarg1: c_double) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_DoubleContainer_get__SWIG_0(jarg1: *const c_void) -> c_double;
    }

    extern "C" {
        pub fn Rust_DoubleContainer_set__SWIG_0(jarg1: *mut c_void, jarg2: c_double);
    }

    extern "C" {
        pub fn Rust_DoubleContainer_add__SWIG_0(jarg1: *mut c_void, jarg2: c_double) -> c_double;
    }

    extern "C" {
        pub fn Rust_delete_DoubleContainer__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_global_int_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_global_double_add__SWIG_0(jarg1: c_double, jarg2: c_double) -> c_double;
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn global_int_add_int_int(a: i32, b: i32) -> i32 {
    unsafe { ffi::Rust_global_int_add__SWIG_0(a, b) }
}

pub fn global_double_add_f64_f64(a: f64, b: f64) -> f64 {
    unsafe { ffi::Rust_global_double_add__SWIG_0(a, b) }
}

/// Rust wrapper for C++ class IntContainer
/// Holds a pointer to the underlying C++ object.
pub struct IntContainer {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class IntContainer
pub trait IntContainerTrait {
    fn get(&self) -> i32;
    fn set(&mut self, v: i32);
    fn add(&mut self, other: i32) -> i32;
}

impl IntContainer {
    pub fn set_value(&self, value: i32) {
        unsafe { ffi::Rust_IntContainer_value_set__SWIG_0(self.ptr, value) }
    }
}

impl IntContainer {
    pub fn value(&self) -> i32 {
        unsafe { ffi::Rust_IntContainer_value_get__SWIG_0(self.ptr) }
    }
}

impl IntContainer {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_IntContainer__SWIG_0() },
        }
    }
}

impl IntContainer {
    pub fn new_int(v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_IntContainer__SWIG_1(v) },
        }
    }
}

impl Drop for IntContainer {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_IntContainer__SWIG_0(self.ptr) }
    }
}

impl IntContainer {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl IntContainerTrait for IntContainer {
    fn get(&self) -> i32 {
        unsafe { ffi::Rust_IntContainer_get__SWIG_0(self.ptr) }
    }
    fn set(&mut self, v: i32) {
        unsafe { ffi::Rust_IntContainer_set__SWIG_0(self.ptr, v) }
    }
    fn add(&mut self, other: i32) -> i32 {
        unsafe { ffi::Rust_IntContainer_add__SWIG_0(self.ptr, other) }
    }
}

/// Rust wrapper for C++ class DoubleContainer
/// Holds a pointer to the underlying C++ object.
pub struct DoubleContainer {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class DoubleContainer
pub trait DoubleContainerTrait {
    fn get(&self) -> f64;
    fn set(&mut self, v: f64);
    fn add(&mut self, other: f64) -> f64;
}

impl DoubleContainer {
    pub fn set_value(&self, value: f64) {
        unsafe { ffi::Rust_DoubleContainer_value_set__SWIG_0(self.ptr, value) }
    }
}

impl DoubleContainer {
    pub fn value(&self) -> f64 {
        unsafe { ffi::Rust_DoubleContainer_value_get__SWIG_0(self.ptr) }
    }
}

impl DoubleContainer {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_DoubleContainer__SWIG_0() },
        }
    }
}

impl DoubleContainer {
    pub fn new_f64(v: f64) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_DoubleContainer__SWIG_1(v) },
        }
    }
}

impl Drop for DoubleContainer {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_DoubleContainer__SWIG_0(self.ptr) }
    }
}

impl DoubleContainer {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl DoubleContainerTrait for DoubleContainer {
    fn get(&self) -> f64 {
        unsafe { ffi::Rust_DoubleContainer_get__SWIG_0(self.ptr) }
    }
    fn set(&mut self, v: f64) {
        unsafe { ffi::Rust_DoubleContainer_set__SWIG_0(self.ptr, v) }
    }
    fn add(&mut self, other: f64) -> f64 {
        unsafe { ffi::Rust_DoubleContainer_add__SWIG_0(self.ptr, other) }
    }
}

