// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_maxint__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_maxdouble__SWIG_0(jarg1: c_double, jarg2: c_double) -> c_double;
    }

    extern "C" {
        pub fn Rust_new_vecint__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecint_get__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecint_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: *mut c_void);
    }

    extern "C" {
        pub fn Rust_vecint_testconst__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_delete_vecint__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_vecdouble__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecdouble_get__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecdouble_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: *mut c_void);
    }

    extern "C" {
        pub fn Rust_vecdouble_testconst__SWIG_0(jarg1: *mut c_void, jarg2: c_double);
    }

    extern "C" {
        pub fn Rust_delete_vecdouble__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_maxintp__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_vecintp__SWIG_0(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecintp_get__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_vecintp_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int, jarg3: *mut c_void);
    }

    extern "C" {
        pub fn Rust_vecintp_testconst__SWIG_0(jarg1: *mut c_void, jarg2: *mut c_void);
    }

    extern "C" {
        pub fn Rust_delete_vecintp__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

pub fn maxint_int_int(a: i32, b: i32) -> i32 {
    unsafe { ffi::Rust_maxint__SWIG_0(a, b) }
}

pub fn maxdouble_f64_f64(a: f64, b: f64) -> f64 {
    unsafe { ffi::Rust_maxdouble__SWIG_0(a, b) }
}

/// Rust wrapper for C++ class vecint
/// Holds a pointer to the underlying C++ object.
pub struct vecint {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class vecint
pub trait vecintTrait {
    fn get(&mut self, index: i32) -> i32;
    fn set(&mut self, index: i32, val: *mut c_void);
    fn testconst(&mut self, x: i32);
}

impl vecint {
    pub fn new_int(_sz: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_vecint__SWIG_0(_sz) },
        }
    }
}

impl Drop for vecint {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_vecint__SWIG_0(self.ptr) }
    }
}

impl vecint {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl vecintTrait for vecint {
    fn get(&mut self, index: i32) -> i32 {
        unsafe { ffi::Rust_vecint_get__SWIG_0(self.ptr, index) }
    }
    fn set(&mut self, index: i32, val: *mut c_void) {
        unsafe { ffi::Rust_vecint_set__SWIG_0(self.ptr, index, val) }
    }
    fn testconst(&mut self, x: i32) {
        unsafe { ffi::Rust_vecint_testconst__SWIG_0(self.ptr, x) }
    }
}

/// Rust wrapper for C++ class vecdouble
/// Holds a pointer to the underlying C++ object.
pub struct vecdouble {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class vecdouble
pub trait vecdoubleTrait {
    fn get(&mut self, index: i32) -> f64;
    fn set(&mut self, index: i32, val: *mut c_void);
    fn testconst(&mut self, x: f64);
}

impl vecdouble {
    pub fn new_int(_sz: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_vecdouble__SWIG_0(_sz) },
        }
    }
}

impl Drop for vecdouble {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_vecdouble__SWIG_0(self.ptr) }
    }
}

impl vecdouble {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl vecdoubleTrait for vecdouble {
    fn get(&mut self, index: i32) -> f64 {
        unsafe { ffi::Rust_vecdouble_get__SWIG_0(self.ptr, index) }
    }
    fn set(&mut self, index: i32, val: *mut c_void) {
        unsafe { ffi::Rust_vecdouble_set__SWIG_0(self.ptr, index, val) }
    }
    fn testconst(&mut self, x: f64) {
        unsafe { ffi::Rust_vecdouble_testconst__SWIG_0(self.ptr, x) }
    }
}

/// Rust wrapper for C++ class vecintp
/// Holds a pointer to the underlying C++ object.
pub struct vecintp {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class vecintp
pub trait vecintpTrait {
    fn get(&mut self, index: i32) -> int;
    fn set(&mut self, index: i32, val: *mut c_void);
    fn testconst(&mut self, x: *mut c_void);
}

impl vecintp {
    pub fn new_int(_sz: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_vecintp__SWIG_0(_sz) },
        }
    }
}

impl Drop for vecintp {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_vecintp__SWIG_0(self.ptr) }
    }
}

impl vecintp {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl vecintpTrait for vecintp {
    fn get(&mut self, index: i32) -> int {
        unsafe { std::mem::transmute::<i32, int>(ffi::Rust_vecintp_get__SWIG_0(self.ptr, index)) }
    }
    fn set(&mut self, index: i32, val: *mut c_void) {
        unsafe { ffi::Rust_vecintp_set__SWIG_0(self.ptr, index, val) }
    }
    fn testconst(&mut self, x: *mut c_void) {
        unsafe { ffi::Rust_vecintp_testconst__SWIG_0(self.ptr, x) }
    }
}

