// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_Base_base_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_Base_base_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Base__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Base__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Base__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Base_base_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_Base_virtual_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_Derived_derived_value_set__SWIG_0(jarg1: *mut c_void, jarg2: c_int);
    }

    extern "C" {
        pub fn Rust_Derived_derived_value_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_Derived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_Derived__SWIG_1(jarg1: c_int, jarg2: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Derived_derived_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_Derived_virtual_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_Derived__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_GrandDerived__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_GrandDerived_grand_method__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_GrandDerived__SWIG_0(jarg1: *mut c_void);
    }

}

use std::os::raw::*;

// Safe wrapper functions

/// Rust wrapper for C++ class Base
/// Holds a pointer to the underlying C++ object.
pub struct Base {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Base
pub trait BaseTrait {
    fn base_method(&mut self) -> i32;
    fn virtual_method(&mut self) -> i32;
}

impl Base {
    pub fn set_base_value(&self, base_value: i32) {
        unsafe { ffi::Rust_Base_base_value_set__SWIG_0(self.ptr, base_value) }
    }
}

impl Base {
    pub fn base_value(&self) -> i32 {
        unsafe { ffi::Rust_Base_base_value_get__SWIG_0(self.ptr) }
    }
}

impl Base {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Base__SWIG_0() },
        }
    }
}

impl Base {
    pub fn new_int(v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Base__SWIG_1(v) },
        }
    }
}

impl Drop for Base {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Base__SWIG_0(self.ptr) }
    }
}

impl Base {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BaseTrait for Base {
    fn base_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Base_base_method__SWIG_0(self.ptr) }
    }
    fn virtual_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Base_virtual_method__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Derived
/// Holds a pointer to the underlying C++ object.
pub struct Derived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Derived
pub trait DerivedTrait: BaseTrait {
    fn derived_method(&mut self) -> i32;
    fn virtual_method(&mut self) -> i32;
}

impl Derived {
    pub fn set_derived_value(&self, derived_value: i32) {
        unsafe { ffi::Rust_Derived_derived_value_set__SWIG_0(self.ptr, derived_value) }
    }
}

impl Derived {
    pub fn derived_value(&self) -> i32 {
        unsafe { ffi::Rust_Derived_derived_value_get__SWIG_0(self.ptr) }
    }
}

impl Derived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Derived__SWIG_0() },
        }
    }
}

impl Derived {
    pub fn new_int_int(base_v: i32, derived_v: i32) -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Derived__SWIG_1(base_v, derived_v) },
        }
    }
}

impl Drop for Derived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Derived__SWIG_0(self.ptr) }
    }
}

impl Derived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Base
    pub fn as_Base(&self) -> &Base {
        // SAFETY: The pointer is valid and points to a Base
        unsafe { &*(self.ptr as *const Base) }
    }

    /// Upcast to base class Base (mutable)
    pub fn as_Base_mut(&mut self) -> &mut Base {
        // SAFETY: The pointer is valid and points to a Base
        unsafe { &mut *(self.ptr as *mut Base) }
    }
}

impl DerivedTrait for Derived {
    fn derived_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Derived_derived_method__SWIG_0(self.ptr) }
    }
    fn virtual_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Derived_virtual_method__SWIG_0(self.ptr) }
    }
}

// Base trait implementation for inheritance
impl BaseTrait for Derived {
    fn base_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Base_base_method__SWIG_0(self.ptr) }
    }
    fn virtual_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Base_virtual_method__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class GrandDerived
/// Holds a pointer to the underlying C++ object.
pub struct GrandDerived {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class GrandDerived
pub trait GrandDerivedTrait: DerivedTrait {
    fn grand_method(&mut self) -> i32;
}

impl GrandDerived {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_GrandDerived__SWIG_0() },
        }
    }
}

impl Drop for GrandDerived {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_GrandDerived__SWIG_0(self.ptr) }
    }
}

impl GrandDerived {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Derived
    pub fn as_Derived(&self) -> &Derived {
        // SAFETY: The pointer is valid and points to a Derived
        unsafe { &*(self.ptr as *const Derived) }
    }

    /// Upcast to base class Derived (mutable)
    pub fn as_Derived_mut(&mut self) -> &mut Derived {
        // SAFETY: The pointer is valid and points to a Derived
        unsafe { &mut *(self.ptr as *mut Derived) }
    }
}

impl GrandDerivedTrait for GrandDerived {
    fn grand_method(&mut self) -> i32 {
        unsafe { ffi::Rust_GrandDerived_grand_method__SWIG_0(self.ptr) }
    }
}

// Base trait implementation for inheritance
impl DerivedTrait for GrandDerived {
    fn derived_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Derived_derived_method__SWIG_0(self.ptr) }
    }
    fn virtual_method(&mut self) -> i32 {
        unsafe { ffi::Rust_Derived_virtual_method__SWIG_0(self.ptr) }
    }
}

