//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class test {
  public static int outer_var {
    set {
      testPINVOKE.outer_var_set(value);
    } 
    get {
      int ret = testPINVOKE.outer_var_get();
      return ret;
    } 
  }

  public static int outer_func() {
    int ret = testPINVOKE.outer_func();
    return ret;
  }

  public static int inner_var {
    set {
      testPINVOKE.inner_var_set(value);
    } 
    get {
      int ret = testPINVOKE.inner_var_get();
      return ret;
    } 
  }

  public static int inner_func() {
    int ret = testPINVOKE.inner_func();
    return ret;
  }

  public static int my_global_check_status(int code) {
    int ret = testPINVOKE.my_global_check_status(code);
    return ret;
  }

}
