// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_OverloadClass__SWIG_2(jarg1: c_double) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_0(jarg1: *mut c_void, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_1(jarg1: *mut c_void, jarg2: c_double) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_process__SWIG_2(jarg1: *mut c_void, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_get__SWIG_0(jarg1: *mut c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_OverloadClass_get__SWIG_1(jarg1: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_delete_OverloadClass__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_add__SWIG_0(jarg1: c_int, jarg2: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_add__SWIG_1(jarg1: c_int, jarg2: c_int, jarg3: c_int) -> c_int;
    }

    extern "C" {
        pub fn Rust_add__SWIG_2(jarg1: c_double, jarg2: c_double) -> c_double;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class OverloadClass
/// Holds a pointer to the underlying C++ object.
pub struct OverloadClass {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class OverloadClass
pub trait OverloadClassTrait {
}

impl OverloadClass {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_0() },
        }
    }
}

impl OverloadClass {
    pub fn new_int() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_1() },
        }
    }
}

impl OverloadClass {
    pub fn new_f64() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_OverloadClass__SWIG_2() },
        }
    }
}

impl Drop for OverloadClass {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_OverloadClass__SWIG_0(self.ptr) }
    }
}

impl OverloadClass {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl OverloadClassTrait for OverloadClass {
}

/// Trait for overload resolution of OverloadClass::process
pub trait OverloadClass_process {
    type Output;
    fn call(self, obj: &mut OverloadClass) -> Self::Output;
}

/// Trait for overload resolution of OverloadClass::get
pub trait OverloadClass_get {
    type Output;
    fn call(self, obj: &mut OverloadClass) -> Self::Output;
}

impl OverloadClass_process for i32 {
    type Output = i32;
    fn call(self, obj: &mut OverloadClass) -> Self::Output {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_0(obj.ptr, self) }
    }
}

impl OverloadClass_process for f64 {
    type Output = i32;
    fn call(self, obj: &mut OverloadClass) -> Self::Output {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_1(obj.ptr, self) }
    }
}

impl OverloadClass_process for (i32, i32) {
    type Output = i32;
    fn call(self, obj: &mut OverloadClass) -> Self::Output {
        unsafe { ffi::Rust_OverloadClass_process__SWIG_2(obj.ptr, self.0, self.1) }
    }
}

impl OverloadClass_get for () {
    type Output = i32;
    fn call(self, obj: &mut OverloadClass) -> Self::Output {
        unsafe { ffi::Rust_OverloadClass_get__SWIG_0(obj.ptr) }
    }
}

impl OverloadClass_get for () {
    type Output = i32;
    fn call(self, obj: &mut OverloadClass) -> Self::Output {
        unsafe { ffi::Rust_OverloadClass_get__SWIG_1(obj.ptr) }
    }
}

impl OverloadClass {
    /// Unified entry point for overloaded method process
    pub fn process<P: OverloadClass_process>(&mut self, p: P) -> P::Output {
        p.call(self)
    }

    /// Unified entry point for overloaded method get
    pub fn get<P: OverloadClass_get>(&mut self, p: P) -> P::Output {
        p.call(self)
    }

}

pub fn add_int_int(a: i32, b: i32) -> i32 {
    unsafe { ffi::Rust_add__SWIG_0(a, b) }
}

pub fn add_int_int_int(a: i32, b: i32, c: i32) -> i32 {
    unsafe { ffi::Rust_add__SWIG_1(a, b, c) }
}

pub fn add_f64_f64(a: f64, b: f64) -> f64 {
    unsafe { ffi::Rust_add__SWIG_2(a, b) }
}

