// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_a__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_new_RealA__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_RealA__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_B_testA__SWIG_0(jarg1: *mut c_void, jarg2: *const c_void) -> c_int;
    }

    extern "C" {
        pub fn Rust_new_B__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_B__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BBB__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BBB__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_new_BB__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_new_BB__SWIG_1(jarg1: c_int) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_aa_var__SWIG_0() -> c_int;
    }

    extern "C" {
        pub fn Rust_BB_aa_method__SWIG_0(jarg1: *mut c_void, jarg2: c_double) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_BB_aa_static_method__SWIG_0(jarg1: c_uchar) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_aa_static_method__SWIG_0(jarg1: c_uchar) -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_BB__SWIG_0(jarg1: *mut c_void);
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class RealA
/// Holds a pointer to the underlying C++ object.
pub struct RealA {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class RealA
pub trait RealATrait {
}

impl RealA {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_RealA__SWIG_0() },
        }
    }
}

impl Drop for RealA {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_RealA__SWIG_0(self.ptr) }
    }
}

impl RealA {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl RealATrait for RealA {
}

/// Rust wrapper for C++ class B
/// Holds a pointer to the underlying C++ object.
pub struct B {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class B
pub trait BTrait {
    fn testA(&self) -> i32;
}

impl B {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_B__SWIG_0() },
        }
    }
}

impl Drop for B {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_B__SWIG_0(self.ptr) }
    }
}

impl B {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BTrait for B {
    fn testA(&self, a: *mut c_void) -> i32 {
        unsafe { ffi::Rust_B_testA__SWIG_0(self.ptr, a) }
    }
}

/// Rust wrapper for C++ class BBB
/// Holds a pointer to the underlying C++ object.
pub struct BBB {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BBB
pub trait BBBTrait {
}

impl BBB {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BBB__SWIG_0() },
        }
    }
}

impl Drop for BBB {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BBB__SWIG_0(self.ptr) }
    }
}

impl BBB {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BBBTrait for BBB {
}

/// Rust wrapper for C++ class BB
/// Holds a pointer to the underlying C++ object.
pub struct BB {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class BB
pub trait BBTrait {
    fn aa_method(&mut self, d: f64) -> i32;
    fn aa_static_method(&mut self, b: bool) -> i32;
}

impl BB {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BB__SWIG_0() },
        }
    }
}

impl BB {
    pub fn new_int() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_BB__SWIG_1() },
        }
    }
}

impl BB {
    pub fn BB_aa_static_method_bool(b: bool) -> *mut c_void {
        unsafe { ffi::Rust_BB_aa_static_method__SWIG_0(b) }
    }
}

impl BB {
    pub fn aa_static_method_bool(b: bool) -> *mut c_void {
        unsafe { ffi::Rust_aa_static_method__SWIG_0(b) }
    }
}

impl Drop for BB {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_BB__SWIG_0(self.ptr) }
    }
}

impl BB {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl BBTrait for BB {
    fn aa_method(&mut self, d: f64) -> i32 {
        unsafe { ffi::Rust_BB_aa_method__SWIG_0(self.ptr, d) }
    }
    fn aa_static_method(&mut self, b: bool) -> i32 {
        unsafe { ffi::Rust_aa_static_method__SWIG_0(self.ptr, b) }
    }
}

