// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.

mod ffi {
    #![allow(non_snake_case)]
    #![allow(non_camel_case_types)]
    #![allow(dead_code)]

    use std::os::raw::*;

    extern "C" {
        pub fn Rust_delete_Foo__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Foo_blah__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Foo__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_Bar_blah__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Bar__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Bar__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_do_blah__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_delete_Spam__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Spam_blah__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_Spam_far1__SWIG_0(jarg1: *mut c_void) -> *const c_char;
    }

    extern "C" {
        pub fn Rust_new_Spam__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_delete_Grok__SWIG_0(jarg1: *mut c_void);
    }

    extern "C" {
        pub fn Rust_Grok_blah__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

    extern "C" {
        pub fn Rust_new_Grok__SWIG_0() -> *mut c_void;
    }

    extern "C" {
        pub fn Rust_do_blah2__SWIG_0(jarg1: *mut c_void) -> *mut c_char;
    }

}

// Safe wrapper functions

/// Rust wrapper for C++ class Foo
/// Holds a pointer to the underlying C++ object.
pub struct Foo {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Foo
pub trait FooTrait {
    fn blah(&mut self) -> c_char;
}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Foo__SWIG_0(self.ptr) }
    }
}

impl Foo {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Foo__SWIG_0() },
        }
    }
}

impl Foo {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl FooTrait for Foo {
    fn blah(&mut self) -> c_char {
        unsafe { ffi::Rust_Foo_blah__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Bar
/// Holds a pointer to the underlying C++ object.
pub struct Bar {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Bar
pub trait BarTrait: FooTrait {
    fn blah(&mut self) -> c_char;
}

impl Bar {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Bar__SWIG_0() },
        }
    }
}

impl Drop for Bar {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Bar__SWIG_0(self.ptr) }
    }
}

impl Bar {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Foo
    pub fn as_Foo(&self) -> &Foo {
        // SAFETY: The pointer is valid and points to a Foo
        unsafe { &*(self.ptr as *const Foo) }
    }

    /// Upcast to base class Foo (mutable)
    pub fn as_Foo_mut(&mut self) -> &mut Foo {
        // SAFETY: The pointer is valid and points to a Foo
        unsafe { &mut *(self.ptr as *mut Foo) }
    }
}

impl BarTrait for Bar {
    fn blah(&mut self) -> c_char {
        unsafe { ffi::Rust_Bar_blah__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Spam
/// Holds a pointer to the underlying C++ object.
pub struct Spam {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Spam
pub trait SpamTrait {
    fn blah(&mut self) -> c_char;
    fn far1(&mut self) -> c_char;
}

impl Drop for Spam {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Spam__SWIG_0(self.ptr) }
    }
}

impl Spam {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Spam__SWIG_0() },
        }
    }
}

impl Spam {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }
}

impl SpamTrait for Spam {
    fn blah(&mut self) -> c_char {
        unsafe { ffi::Rust_Spam_blah__SWIG_0(self.ptr) }
    }
    fn far1(&self) -> c_char {
        unsafe { ffi::Rust_Spam_far1__SWIG_0(self.ptr) }
    }
}

/// Rust wrapper for C++ class Grok
/// Holds a pointer to the underlying C++ object.
pub struct Grok {
    /// Pointer to the C++ object
    ptr: *mut c_void,
}

/// Trait defining the interface for C++ class Grok
pub trait GrokTrait: SpamTrait {
    fn blah(&mut self) -> c_char;
}

impl Drop for Grok {
    fn drop(&mut self) {
        unsafe { ffi::Rust_delete_Grok__SWIG_0(self.ptr) }
    }
}

impl Grok {
    pub fn new() -> Self {
        Self {
            ptr: unsafe { ffi::Rust_new_Grok__SWIG_0() },
        }
    }
}

impl Grok {
    /// Get the underlying C++ pointer (read-only)
    pub fn ptr(&self) -> *const c_void {
        self.ptr as *const c_void
    }

    /// Get the underlying C++ pointer (mutable)
    pub fn ptr_mut(&mut self) -> *mut c_void {
        self.ptr
    }

    /// Upcast to base class Spam
    pub fn as_Spam(&self) -> &Spam {
        // SAFETY: The pointer is valid and points to a Spam
        unsafe { &*(self.ptr as *const Spam) }
    }

    /// Upcast to base class Spam (mutable)
    pub fn as_Spam_mut(&mut self) -> &mut Spam {
        // SAFETY: The pointer is valid and points to a Spam
        unsafe { &mut *(self.ptr as *mut Spam) }
    }
}

impl GrokTrait for Grok {
    fn blah(&mut self) -> c_char {
        unsafe { ffi::Rust_Grok_blah__SWIG_0(self.ptr) }
    }
}

